import type { DeckTemplate } from "./types";

export const DECK_TEMPLATES: DeckTemplate[] = [
  {
    id: "founder-blueprint",
    name: "创始人可复制蓝图汇报",
    scenario: "组织能力转移",
    description: "把创始人判断变成组织系统的进展汇报，适合董事会 / 管理层。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "创始人可复制蓝图", subtitle: "把关键判断变成组织能执行的系统", note: "公司名 · 2026 Q2" },
      { layout: "bullets", title: "为什么现在做", bullets: ["创始人一离开，决策变慢、标准走样、关键知识失传", "20–200 人阶段最该把隐性判断显性化", "目标：14 天产出可验证蓝图，并完成一次真实交接"] },
      { layout: "metrics", title: "当前组织健康", metrics: [{ label: "可复制度", value: "42%" }, { label: "创始人依赖", value: "78%" }, { label: "抗脆弱韧性", value: "46%" }, { label: "已批准资产", value: "3" }] },
      { layout: "twoColumn", title: "关键能力与依赖", columns: [{ heading: "高依赖（先转移）", bullets: ["大客户定价拍板", "核心架构知识", "招聘高管判断"] }, { heading: "可复制度", bullets: ["报价规则化中", "架构待文档化", "招聘标准初稿"] }] },
      { layout: "timeline", title: "90 天去依赖路径", steps: [{ label: "第 1–2 周", detail: "证据库 + 诊断" }, { label: "第 3–6 周", detail: "决策规则 + 手册" }, { label: "第 7–12 周", detail: "演练 + 授权 + 复审" }] },
      { layout: "quote", quote: "好规则让团队做出一致判断，而不是机械服从。", author: "承策方法" },
      { layout: "closing", title: "下一步", subtitle: "本月把定价拍板拆成决策规则并指定第二责任人", note: "讨论 / 提问" },
    ],
  },
  {
    id: "monthly-business-review",
    name: "月度经营复盘",
    scenario: "经营管理",
    description: "月度业务回顾：指标、亮点、问题、下月重点。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "月度经营复盘", subtitle: "2026 年 6 月", note: "经营管理团队" },
      { layout: "metrics", title: "核心指标", metrics: [{ label: "营收", value: "¥1.2M" }, { label: "环比", value: "+14%" }, { label: "新签", value: "23" }, { label: "毛利", value: "61%" }] },
      { layout: "bullets", title: "本月亮点", bullets: ["大客户续约率达 95%", "新产品线贡献 18% 营收", "获客成本下降 12%"] },
      { layout: "twoColumn", title: "问题与对策", columns: [{ heading: "问题", bullets: ["交付周期偏长", "客成团队超载"] }, { heading: "对策", bullets: ["标准化交付清单", "招聘 + 自动化分流"] }] },
      { layout: "bullets", title: "下月三件最重要的事", bullets: ["把交付周期压缩到 3 周内", "上线自助续约流程", "完成 Q3 招聘计划"] },
      { layout: "closing", title: "Owner & 截止", subtitle: "每项有负责人、有日期、有验证", note: "谢谢" },
    ],
  },
  {
    id: "investor-pitch",
    name: "投资人路演",
    scenario: "融资",
    description: "种子 / A 轮路演的标准叙事结构。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "公司名", subtitle: "一句话说清你做什么、为谁、价值", note: "融资路演 · 2026" },
      { layout: "bullets", title: "问题", bullets: ["目标客户正承受的真实痛点", "现有方案为何不够好", "为什么现在是时机"] },
      { layout: "bullets", title: "解决方案", bullets: ["你的产品如何根治问题", "与替代方案的关键差异", "一句可记住的定位"] },
      { layout: "metrics", title: "市场与牵引", metrics: [{ label: "TAM", value: "¥80B" }, { label: "MRR", value: "¥300K" }, { label: "环比", value: "+22%" }, { label: "留存", value: "94%" }] },
      { layout: "twoColumn", title: "商业模式 & 护城河", columns: [{ heading: "如何赚钱", bullets: ["按席位订阅", "增值服务"] }, { heading: "护城河", bullets: ["数据飞轮", "切换成本"] }] },
      { layout: "timeline", title: "里程碑", steps: [{ label: "已完成", detail: "PMF + 首批付费" }, { label: "本轮", detail: "复制增长引擎" }, { label: "12 个月", detail: "进入第二市场" }] },
      { layout: "metrics", title: "本轮", metrics: [{ label: "募集", value: "¥20M" }, { label: "估值", value: "¥120M" }, { label: "跑道", value: "24 个月" }, { label: "用途", value: "增长 / 研发" }] },
      { layout: "closing", title: "一起把它做大", subtitle: "联系方式 · 邮箱 / 微信", note: "Thank you" },
    ],
  },
  {
    id: "sales-proposal",
    name: "B2B 销售提案",
    scenario: "销售",
    description: "面向客户的价值主张与方案提案。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "致 [客户名] 的合作方案", subtitle: "用 [产品] 解决 [关键问题]", note: "提案 · 2026" },
      { layout: "bullets", title: "我们对你现状的理解", bullets: ["你正面临的挑战", "它对业务的代价", "你期望达到的结果"] },
      { layout: "twoColumn", title: "方案概览", columns: [{ heading: "我们提供", bullets: ["核心模块 A", "核心模块 B", "实施与培训"] }, { heading: "你将获得", bullets: ["效率提升", "成本下降", "可量化结果"] }] },
      { layout: "timeline", title: "落地路径", steps: [{ label: "第 1 周", detail: "对齐与配置" }, { label: "第 2–4 周", detail: "试点上线" }, { label: "第 5 周+", detail: "全量推广" }] },
      { layout: "metrics", title: "预期 ROI", metrics: [{ label: "效率", value: "+30%" }, { label: "成本", value: "-18%" }, { label: "回本", value: "4 个月" }, { label: "NPS", value: "+20" }] },
      { layout: "quote", quote: "我们只为可验证的结果负责，而不是功能清单。", author: "你的团队" },
      { layout: "closing", title: "下一步", subtitle: "确认试点范围 · 启动时间", note: "期待合作" },
    ],
  },
  {
    id: "product-launch",
    name: "产品发布",
    scenario: "产品",
    description: "新产品 / 大版本对内外发布。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "全新 [产品名]", subtitle: "一句话说清它为用户带来什么", note: "发布 · 2026" },
      { layout: "section", title: "01", subtitle: "我们要解决的问题" },
      { layout: "bullets", title: "三大新能力", bullets: ["能力一：更快", "能力二：更省", "能力三：更稳"] },
      { layout: "twoColumn", title: "之前 vs 现在", columns: [{ heading: "之前", bullets: ["手动、易错", "割裂体验"] }, { heading: "现在", bullets: ["自动、可靠", "一体化"] }] },
      { layout: "metrics", title: "早期数据", metrics: [{ label: "提速", value: "3×" }, { label: "采用", value: "68%" }, { label: "满意", value: "4.7/5" }] },
      { layout: "timeline", title: "发布节奏", steps: [{ label: "今天", detail: "灰度开放" }, { label: "下周", detail: "全量上线" }, { label: "下月", detail: "生态集成" }] },
      { layout: "closing", title: "现在就试用", subtitle: "入口 / 文档 / 反馈渠道", note: "Let's ship" },
    ],
  },
  {
    id: "quarterly-okr",
    name: "季度 OKR 对齐",
    scenario: "目标管理",
    description: "季度目标与关键结果对齐。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "2026 Q3 OKR", subtitle: "对齐目标，聚焦少数关键结果", note: "全员对齐" },
      { layout: "bullets", title: "公司级目标", bullets: ["O1：成为细分市场首选", "O2：建立可复制增长引擎", "O3：组织反脆弱"] },
      { layout: "twoColumn", title: "O1 关键结果", columns: [{ heading: "KR", bullets: ["NPS ≥ 50", "续约 ≥ 92%"] }, { heading: "Owner", bullets: ["产品", "客成"] }] },
      { layout: "twoColumn", title: "O2 关键结果", columns: [{ heading: "KR", bullets: ["新签 +40%", "CAC -15%"] }, { heading: "Owner", bullets: ["市场", "销售"] }] },
      { layout: "metrics", title: "上季回顾", metrics: [{ label: "达成率", value: "73%" }, { label: "超额", value: "2 项" }, { label: "未达", value: "1 项" }] },
      { layout: "closing", title: "承诺与节奏", subtitle: "双周 check-in，季末复盘", note: "Go" },
    ],
  },
  {
    id: "consulting-diagnosis",
    name: "咨询诊断报告",
    scenario: "咨询交付",
    description: "面向客户的组织 / 业务诊断结论与建议。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "组织诊断报告", subtitle: "[客户名] · 现状、风险与路径", note: "咨询交付 · 2026" },
      { layout: "section", title: "诊断", subtitle: "我们看到了什么" },
      { layout: "metrics", title: "健康度评分", metrics: [{ label: "可复制度", value: "41%" }, { label: "依赖风险", value: "高" }, { label: "决策一致", value: "中" }, { label: "知识沉淀", value: "低" }] },
      { layout: "bullets", title: "三个核心发现", bullets: ["关键判断集中在少数人", "缺乏可执行的决策规则", "知识未沉淀为组织资产"] },
      { layout: "twoColumn", title: "风险与影响", columns: [{ heading: "风险", bullets: ["关键人离职", "标准走样"] }, { heading: "影响", bullets: ["交付不稳定", "增长受限"] }] },
      { layout: "timeline", title: "建议路径", steps: [{ label: "0–30 天", detail: "诊断 + 规则化" }, { label: "30–60 天", detail: "手册 + 演练" }, { label: "60–90 天", detail: "授权 + 复审" }] },
      { layout: "closing", title: "建议下一步", subtitle: "从最高风险的一项判断开始转移", note: "Q & A" },
    ],
  },
  {
    id: "team-intro",
    name: "团队介绍 / 招聘",
    scenario: "雇主品牌",
    description: "对外介绍团队、文化与机会。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "和我们一起，把卓越复制出去", subtitle: "我们是谁，为什么值得加入", note: "招聘 · 2026" },
      { layout: "bullets", title: "我们的使命", bullets: ["把判断变成组织能力", "让团队独立交付结果", "做反脆弱的组织"] },
      { layout: "twoColumn", title: "我们看重", columns: [{ heading: "价值观", bullets: ["证据优先", "可复制", "长期主义"] }, { heading: "工作方式", bullets: ["少而精", "高自主", "强复盘"] }] },
      { layout: "metrics", title: "团队", metrics: [{ label: "成员", value: "48" }, { label: "在招", value: "6" }, { label: "城市", value: "3" }, { label: "满意度", value: "4.6/5" }] },
      { layout: "quote", quote: "我们不监督人，我们对齐人。", author: "团队信条" },
      { layout: "closing", title: "加入我们", subtitle: "投递入口 / 联系人", note: "期待你" },
    ],
  },
];

export const getDeckTemplate = (id: string): DeckTemplate | undefined => DECK_TEMPLATES.find((t) => t.id === id);
