import type { DeckTemplate } from "../types";

export const FINANCING_TEMPLATES: DeckTemplate[] = [
  {
    id: "seed-pitch",
    name: "天使 / 种子轮路演",
    scenario: "天使融资",
    category: "融资路演",
    description: "适合 Pre-A 前的早期融资，从痛点到 MVP 再到需求验证。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "[公司名]", subtitle: "一句话说清你在解决谁的什么问题", note: "种子轮 · 2026" },
      { layout: "bullets", title: "痛点", bullets: ["目标用户每天在为什么事烦恼", "现有解法有什么本质缺陷", "为什么这个问题现在值得解决"] },
      { layout: "bullets", title: "解决方案", bullets: ["我们如何让用户的生活变得更好", "核心差异：为什么是我们", "一句能让用户转述的定位语"] },
      { layout: "twoColumn", title: "MVP 验证", columns: [{ heading: "已做到", bullets: ["首批真实用户", "留存率数据", "NPS 分数"] }, { heading: "下一步", bullets: ["扩大用户规模", "打磨核心功能", "探索变现路径"] }] },
      { layout: "metrics", title: "市场机会", metrics: [{ label: "TAM", value: "¥XXB" }, { label: "目标客群", value: "XX 万人" }, { label: "ARPU", value: "¥XXX" }, { label: "3年ARR", value: "¥XXM" }] },
      { layout: "bullets", title: "为什么是我们", bullets: ["团队：核心优势与独特背景", "时机：为什么现在窗口打开", "壁垒：数据 / 技术 / 渠道"] },
      { layout: "metrics", title: "本轮融资", metrics: [{ label: "金额", value: "¥XXX 万" }, { label: "用途", value: "产品 + 获客" }, { label: "跑道", value: "18 个月" }, { label: "里程碑", value: "PMF" }] },
      { layout: "closing", title: "一起做第一", subtitle: "联系方式 · [邮箱 / 微信]", note: "Thank you" },
    ],
  },
  {
    id: "series-a-pitch",
    name: "A 轮融资路演",
    scenario: "A 轮融资",
    category: "融资路演",
    description: "已验证 PMF，向机构 VC 展示增长引擎与规模化路径。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "[公司名] A 轮融资", subtitle: "规模化阶段的增长故事", note: "2026" },
      { layout: "metrics", title: "核心牵引", metrics: [{ label: "ARR", value: "¥XXM" }, { label: "MoM", value: "+XX%" }, { label: "NRR", value: "XXX%" }, { label: "付费客户", value: "XXX" }] },
      { layout: "bullets", title: "问题与解法", bullets: ["目标市场的核心痛点", "我们的解法与竞争优势", "已被数字验证的 PMF"] },
      { layout: "twoColumn", title: "产品 & 技术护城河", columns: [{ heading: "产品壁垒", bullets: ["独特数据资产", "深度工作流整合", "高切换成本"] }, { heading: "技术优势", bullets: ["自研核心引擎", "专利 / Know-how", "持续学习飞轮"] }] },
      { layout: "bullets", title: "增长引擎", bullets: ["获客：主渠道 CAC 与 LTV:CAC 比", "扩张：NRR 与同期群留存", "口碑：NPS 与自然引流占比"] },
      { layout: "timeline", title: "18 个月里程碑", steps: [{ label: "0–6 月", detail: "团队扩张 + 产品迭代" }, { label: "6–12 月", detail: "进入第二城市 / 行业" }, { label: "12–18 月", detail: "ARR 翻倍 + B 轮准备" }] },
      { layout: "metrics", title: "本轮", metrics: [{ label: "融资额", value: "¥XXM" }, { label: "Pre 估值", value: "¥XXXM" }, { label: "跑道", value: "24 个月" }, { label: "主要用途", value: "增长 / 研发" }] },
      { layout: "closing", title: "一起定义这个市场", subtitle: "联系方式", note: "期待深聊" },
    ],
  },
  {
    id: "investor-pitch",
    name: "投资人路演（通用）",
    scenario: "融资路演",
    category: "融资路演",
    description: "种子至 A 轮通用叙事结构，8 页经典框架。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "公司名", subtitle: "一句话说清你做什么、为谁、价值", note: "融资路演 · 2026" },
      { layout: "bullets", title: "问题", bullets: ["目标客户正承受的真实痛点", "现有方案为何不够好", "为什么现在是时机"] },
      { layout: "bullets", title: "解决方案", bullets: ["你的产品如何根治问题", "与替代方案的关键差异", "一句可记住的定位"] },
      { layout: "metrics", title: "市场与牵引", metrics: [{ label: "TAM", value: "¥80B" }, { label: "MRR", value: "¥300K" }, { label: "环比", value: "+22%" }, { label: "留存", value: "94%" }] },
      { layout: "twoColumn", title: "商业模式 & 护城河", columns: [{ heading: "如何赚钱", bullets: ["按席位订阅", "增值服务"] }, { heading: "护城河", bullets: ["数据飞轮", "切换成本"] }] },
      { layout: "timeline", title: "里程碑", steps: [{ label: "已完成", detail: "PMF + 首批付费" }, { label: "本轮", detail: "复制增长引擎" }, { label: "12 个月", detail: "进入第二市场" }] },
      { layout: "metrics", title: "本轮", metrics: [{ label: "募集", value: "¥20M" }, { label: "估值", value: "¥120M" }, { label: "跑道", value: "24 个月" }, { label: "用途", value: "增长 / 研发" }] },
      { layout: "closing", title: "一起把它做大", subtitle: "联系方式 · 邮箱 / 微信", note: "Thank you" },
    ],
  },
  {
    id: "demo-day",
    name: "Demo Day 展示",
    scenario: "加速器路演",
    category: "融资路演",
    description: "5 分钟 Demo Day，节奏紧凑，直击要点。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "[公司名]", subtitle: "[一句话定位]", note: "Demo Day · 2026" },
      { layout: "bullets", title: "我们解决什么", bullets: ["谁？目标用户", "什么痛？核心问题", "我们怎么解？"] },
      { layout: "metrics", title: "牵引数据", metrics: [{ label: "用户数", value: "XXXX" }, { label: "MoM", value: "+XX%" }, { label: "收入", value: "¥XXX K" }, { label: "NPS", value: "XX" }] },
      { layout: "bullets", title: "为什么赢", bullets: ["独特技术 / 数据优势", "团队：为什么是我们", "时机：为什么是现在"] },
      { layout: "closing", title: "融 ¥XXX 万，做 XXX", subtitle: "联系方式", note: "谢谢" },
    ],
  },
  {
    id: "strategic-investment",
    name: "战略投资 / 产业资本",
    scenario: "战略融资",
    category: "融资路演",
    description: "面向产业资本或 CVC，强调协同价值而非纯财务回报。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "战略合作与投资机会", subtitle: "与 [投资方] 的协同价值", note: "2026" },
      { layout: "bullets", title: "公司概述", bullets: ["业务方向与核心能力", "当前规模与市场位置", "已验证的核心壁垒"] },
      { layout: "twoColumn", title: "战略协同点", columns: [{ heading: "你们能给我们", bullets: ["渠道 / 客户资源", "技术 / 平台能力", "品牌背书"] }, { heading: "我们能给你们", bullets: ["产品 / 数据补足", "新市场切入", "创新团队"] }] },
      { layout: "metrics", title: "业务健康度", metrics: [{ label: "ARR", value: "¥XXM" }, { label: "增速", value: "+XX%" }, { label: "客户留存", value: "XX%" }, { label: "毛利", value: "XX%" }] },
      { layout: "timeline", title: "协作路线图", steps: [{ label: "Q1", detail: "联合试点" }, { label: "Q2", detail: "渠道整合" }, { label: "Q3–Q4", detail: "深度共建" }] },
      { layout: "closing", title: "开启战略对话", subtitle: "联系方式", note: "期待合作" },
    ],
  },
  {
    id: "fundraising-update",
    name: "投后季度进展更新",
    scenario: "LP / 董事会更新",
    category: "融资路演",
    description: "向已有投资方汇报季度进展、里程碑完成情况和下期计划。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "Q X 投资人更新", subtitle: "[公司名] · 季度进展报告", note: "机密" },
      { layout: "metrics", title: "本季核心数据", metrics: [{ label: "ARR", value: "¥XXM" }, { label: "MoM", value: "+XX%" }, { label: "烧钱率", value: "¥XXX K/月" }, { label: "剩余跑道", value: "XX 个月" }] },
      { layout: "twoColumn", title: "里程碑完成情况", columns: [{ heading: "已完成", bullets: ["目标 A ✓", "目标 B ✓"] }, { heading: "延期 / 调整", bullets: ["目标 C → 原因 + 新计划", "目标 D → 优先级调整"] }] },
      { layout: "bullets", title: "重点事项", bullets: ["最大进展：产品 / 客户 / 团队", "最大挑战：已解决 / 仍在处理", "关键决策与背后逻辑"] },
      { layout: "timeline", title: "下季目标", steps: [{ label: "月 1", detail: "关键里程碑 A" }, { label: "月 2", detail: "关键里程碑 B" }, { label: "月 3", detail: "关键里程碑 C" }] },
      { layout: "closing", title: "需要投资人支持", subtitle: "资源对接 / 客户推荐 / 招聘建议", note: "感谢同行" },
    ],
  },
  {
    id: "brand-financing",
    name: "消费品牌融资路演",
    scenario: "消费品牌融资",
    category: "融资路演",
    description: "消费 / 新零售品牌融资，强调复购、渠道和品牌心智。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "[品牌名]", subtitle: "重新定义 [品类]", note: "融资路演 · 2026" },
      { layout: "bullets", title: "品牌定位", bullets: ["目标人群：谁在买？", "核心差异：为什么买我们？", "品牌心智：一句记得住的话"] },
      { layout: "metrics", title: "业务数据", metrics: [{ label: "月销售额", value: "¥XXM" }, { label: "复购率", value: "XX%" }, { label: "会员数", value: "XX 万" }, { label: "毛利", value: "XX%" }] },
      { layout: "twoColumn", title: "渠道矩阵", columns: [{ heading: "线上", bullets: ["天猫旗舰店", "抖音自播", "私域会员"] }, { heading: "线下", bullets: ["直营门店 XX 家", "经销 XX 城市"] }] },
      { layout: "timeline", title: "品牌增长路径", steps: [{ label: "现在", detail: "核心 SKU 爆款" }, { label: "12 月", detail: "品类延伸" }, { label: "24 月", detail: "出海 / 上市" }] },
      { layout: "closing", title: "成为这代人的首选", subtitle: "联系方式", note: "期待合作" },
    ],
  },
  {
    id: "pre-ipo-story",
    name: "Pre-IPO 故事线",
    scenario: "上市前融资",
    category: "融资路演",
    description: "面向 PE / 上市前机构，强调规模、盈利路径和上市准备。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "[公司名] Pre-IPO", subtitle: "行业领导者的上市准备", note: "机密 · 2026" },
      { layout: "metrics", title: "规模与增长", metrics: [{ label: "ARR", value: "¥XXXM" }, { label: "YoY", value: "+XX%" }, { label: "净利润率", value: "XX%" }, { label: "付费客户", value: "X,XXX" }] },
      { layout: "bullets", title: "行业地位", bullets: ["细分市场 Top 3 的核心依据", "竞争优势与护城河", "客户结构：大客户占比与集中度"] },
      { layout: "twoColumn", title: "财务展望", columns: [{ heading: "历史", bullets: ["2024 ARR ¥XXM", "2025 ARR ¥XXXM"] }, { heading: "预测", bullets: ["2026E ARR ¥XXXXM", "2027E 盈亏平衡"] }] },
      { layout: "bullets", title: "上市准备", bullets: ["治理结构完善，审计已完成", "核心团队锁定，激励到位", "监管合规，无重大法律风险"] },
      { layout: "closing", title: "共同迈向资本市场", subtitle: "联系方式", note: "期待深度交流" },
    ],
  },
];
