import type { DeckTemplate } from "../types";

export const MANAGEMENT_TEMPLATES: DeckTemplate[] = [
  {
    id: "monthly-business-review",
    name: "月度经营复盘",
    scenario: "经营管理",
    category: "经营管理",
    description: "月度业务回顾：指标、亮点、问题、下月重点。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "月度经营复盘", subtitle: "2026 年 6 月", note: "经营管理团队" },
      { layout: "metrics", title: "核心指标", metrics: [{ label: "营收", value: "¥1.2M" }, { label: "环比", value: "+14%" }, { label: "新签", value: "23" }, { label: "毛利", value: "61%" }] },
      { layout: "bullets", title: "本月亮点", bullets: ["大客户续约率达 95%", "新产品线贡献 18% 营收", "获客成本下降 12%"] },
      { layout: "twoColumn", title: "问题与对策", columns: [{ heading: "问题", bullets: ["交付周期偏长", "客成团队超载"] }, { heading: "对策", bullets: ["标准化交付清单", "招聘 + 自动化分流"] }] },
      { layout: "bullets", title: "下月三件最重要的事", bullets: ["把交付周期压缩到 3 周内", "上线自助续约流程", "完成 Q3 招聘计划"] },
      { layout: "closing", title: "Owner & 截止", subtitle: "每项有负责人、有日期、有验证", note: "谢谢" },
    ],
  },
  {
    id: "quarterly-okr",
    name: "季度 OKR 对齐",
    scenario: "目标管理",
    category: "经营管理",
    description: "季度目标与关键结果对齐，全员共识。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "2026 Q3 OKR", subtitle: "对齐目标，聚焦少数关键结果", note: "全员对齐" },
      { layout: "bullets", title: "公司级目标", bullets: ["O1：成为细分市场首选", "O2：建立可复制增长引擎", "O3：组织反脆弱"] },
      { layout: "twoColumn", title: "O1 关键结果", columns: [{ heading: "KR", bullets: ["NPS ≥ 50", "续约 ≥ 92%"] }, { heading: "Owner", bullets: ["产品", "客成"] }] },
      { layout: "twoColumn", title: "O2 关键结果", columns: [{ heading: "KR", bullets: ["新签 +40%", "CAC -15%"] }, { heading: "Owner", bullets: ["市场", "销售"] }] },
      { layout: "metrics", title: "上季回顾", metrics: [{ label: "达成率", value: "73%" }, { label: "超额", value: "2 项" }, { label: "未达", value: "1 项" }] },
      { layout: "closing", title: "承诺与节奏", subtitle: "双周 check-in，季末复盘", note: "Go" },
    ],
  },
  {
    id: "weekly-standup",
    name: "周例会同步",
    scenario: "周例会",
    category: "经营管理",
    description: "团队周会：上周完成、本周计划、风险与协作需求。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "周例会", subtitle: "第 XX 周 · [日期]", note: "[团队名]" },
      { layout: "twoColumn", title: "上周回顾", columns: [{ heading: "完成", bullets: ["事项 A ✓", "事项 B ✓", "事项 C ✓"] }, { heading: "未完成", bullets: ["事项 D → 原因", "事项 E → 下周完成"] }] },
      { layout: "bullets", title: "本周计划", bullets: ["优先事项 1（Owner / 截止）", "优先事项 2（Owner / 截止）", "优先事项 3（Owner / 截止）"] },
      { layout: "bullets", title: "风险 & 需要协作", bullets: ["风险 1：描述 + 应对", "风险 2：描述 + 应对", "需要其他团队支持：XXX"] },
      { layout: "closing", title: "本周一件最重要的事", subtitle: "[关键结果]", note: "加油" },
    ],
  },
  {
    id: "board-meeting",
    name: "董事会汇报",
    scenario: "董事会",
    category: "经营管理",
    description: "向董事会汇报经营状况、战略进展和重大决策。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "董事会汇报", subtitle: "2026 年 Q2 经营报告", note: "机密" },
      { layout: "metrics", title: "Q2 核心经营指标", metrics: [{ label: "营收", value: "¥XXM" }, { label: "YoY", value: "+XX%" }, { label: "净利率", value: "XX%" }, { label: "现金储备", value: "¥XXM" }] },
      { layout: "twoColumn", title: "战略进展", columns: [{ heading: "按计划推进", bullets: ["战略举措 A", "战略举措 B"] }, { heading: "需要讨论", bullets: ["战略决策 C", "资源分配 D"] }] },
      { layout: "bullets", title: "重大风险与应对", bullets: ["风险 1：描述 + 缓解措施", "风险 2：描述 + 缓解措施", "外部环境变化及影响"] },
      { layout: "timeline", title: "Q3 重点计划", steps: [{ label: "7 月", detail: "里程碑 A" }, { label: "8 月", detail: "里程碑 B" }, { label: "9 月", detail: "里程碑 C" }] },
      { layout: "bullets", title: "需要董事会决策", bullets: ["议题 1：背景 + 建议方案 + 所需批准", "议题 2：背景 + 建议方案 + 所需批准"] },
      { layout: "closing", title: "讨论与决议", subtitle: "感谢各位董事的时间", note: "Q & A" },
    ],
  },
  {
    id: "cost-reduction",
    name: "降本增效方案",
    scenario: "成本优化",
    category: "经营管理",
    description: "向管理层展示降本增效诊断结论与落地方案。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "降本增效专项", subtitle: "从诊断到落地的完整路径", note: "2026" },
      { layout: "metrics", title: "现状诊断", metrics: [{ label: "成本增速", value: "+XX%/年" }, { label: "人效", value: "¥XXX K/人" }, { label: "毛利率", value: "XX%" }, { label: "优化空间", value: "¥XXM" }] },
      { layout: "twoColumn", title: "主要成本结构", columns: [{ heading: "人力成本", bullets: ["占总成本 XX%", "冗余岗位识别", "人效提升空间"] }, { heading: "运营成本", bullets: ["SaaS / 工具费用", "外包成本", "流程浪费"] }] },
      { layout: "bullets", title: "优化重点", bullets: ["流程自动化：减少重复性人工", "工具整合：合并冗余系统", "外包优化：重新评估外包边界"] },
      { layout: "timeline", title: "90 天落地计划", steps: [{ label: "第 1 月", detail: "诊断 + 优先级排序" }, { label: "第 2 月", detail: "试点 + 快速见效" }, { label: "第 3 月", detail: "全面推广 + 固化" }] },
      { layout: "metrics", title: "预期成效", metrics: [{ label: "成本节省", value: "¥XXM/年" }, { label: "效率提升", value: "+XX%" }, { label: "回报周期", value: "X 个月" }] },
      { layout: "closing", title: "开始行动", subtitle: "指定 Owner，锁定时间表", note: "执行为先" },
    ],
  },
  {
    id: "founder-blueprint",
    name: "创始人可复制蓝图",
    scenario: "组织能力转移",
    category: "经营管理",
    description: "把创始人判断变成组织系统的进展汇报，适合董事会 / 管理层。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "创始人可复制蓝图", subtitle: "把关键判断变成组织能执行的系统", note: "公司名 · 2026 Q2" },
      { layout: "bullets", title: "为什么现在做", bullets: ["创始人一离开，决策变慢、标准走样、关键知识失传", "20–200 人阶段最该把隐性判断显性化", "目标：14 天产出可验证蓝图，并完成一次真实交接"] },
      { layout: "metrics", title: "当前组织健康", metrics: [{ label: "可复制度", value: "42%" }, { label: "创始人依赖", value: "78%" }, { label: "抗脆弱韧性", value: "46%" }, { label: "已批准资产", value: "3" }] },
      { layout: "twoColumn", title: "关键能力与依赖", columns: [{ heading: "高依赖（先转移）", bullets: ["大客户定价拍板", "核心架构知识", "招聘高管判断"] }, { heading: "可复制度", bullets: ["报价规则化中", "架构待文档化", "招聘标准初稿"] }] },
      { layout: "timeline", title: "90 天去依赖路径", steps: [{ label: "第 1–2 周", detail: "证据库 + 诊断" }, { label: "第 3–6 周", detail: "决策规则 + 手册" }, { label: "第 7–12 周", detail: "演练 + 授权 + 复审" }] },
      { layout: "quote", quote: "好规则让团队做出一致判断，而不是机械服从。", author: "承策方法" },
      { layout: "closing", title: "下一步", subtitle: "本月把定价拍板拆成决策规则并指定第二责任人", note: "讨论 / 提问" },
    ],
  },
  {
    id: "crisis-response",
    name: "危机应对汇报",
    scenario: "危机管理",
    category: "经营管理",
    description: "向管理层或董事会汇报突发危机的现状、应对和预防。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "危机应对报告", subtitle: "[事件名称] · 现状与行动", note: "[日期]" },
      { layout: "bullets", title: "事件概述", bullets: ["发生了什么（时间、地点、规模）", "目前的直接影响", "已知的根本原因"] },
      { layout: "metrics", title: "影响评估", metrics: [{ label: "受影响客户", value: "XX 家" }, { label: "业务损失", value: "¥XXX K" }, { label: "持续时长", value: "X 小时" }, { label: "严重程度", value: "高 / 中" }] },
      { layout: "timeline", title: "应对时间线", steps: [{ label: "发现", detail: "XX:XX 发现异常" }, { label: "响应", detail: "XX:XX 启动应急" }, { label: "恢复", detail: "XX:XX 服务恢复" }] },
      { layout: "twoColumn", title: "短期 & 长期措施", columns: [{ heading: "已采取", bullets: ["紧急修复措施", "客户沟通方案", "临时规避方案"] }, { heading: "后续计划", bullets: ["根本原因整改", "监控体系升级", "流程优化"] }] },
      { layout: "closing", title: "防止复发", subtitle: "Owner / 时间表 / 验收标准", note: "汲取教训，持续改进" },
    ],
  },
  {
    id: "budget-review",
    name: "年度预算审批",
    scenario: "预算管理",
    category: "经营管理",
    description: "向管理层提交部门或公司年度预算计划，争取资源支持。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "2027 年度预算计划", subtitle: "[部门名] · 资源申请与目标承诺", note: "预算审批 · 2026" },
      { layout: "metrics", title: "2026 预算执行情况", metrics: [{ label: "预算总额", value: "¥XXM" }, { label: "实际使用", value: "¥XXM" }, { label: "执行率", value: "XX%" }, { label: "ROI", value: "X.X" }] },
      { layout: "bullets", title: "2027 核心目标", bullets: ["目标 1：指标 + 上年对比", "目标 2：指标 + 上年对比", "目标 3：指标 + 上年对比"] },
      { layout: "twoColumn", title: "预算结构", columns: [{ heading: "主要支出项", bullets: ["人力：¥XXM (XX%)", "市场：¥XXM (XX%)", "技术：¥XXM (XX%)"] }, { heading: "增量说明", bullets: ["新增预算 ¥XXM 用于 XXX", "对比去年增加 XX%", "关键假设：增长 XX%"] }] },
      { layout: "timeline", title: "关键节点", steps: [{ label: "Q1", detail: "核心基础设施投入" }, { label: "Q2", detail: "增长引擎启动" }, { label: "Q3–Q4", detail: "规模化与优化" }] },
      { layout: "closing", title: "请求批准", subtitle: "总预算 ¥XXM · 核心承诺：[目标]", note: "感谢支持" },
    ],
  },
];
