import type { DeckTemplate } from "../types";

// ── 教育培训 ───────────────────────────────────────────────
export const EDUCATION_TEMPLATES: DeckTemplate[] = [
  {
    id: "training-course",
    name: "内训课程开场",
    scenario: "企业培训",
    category: "教育培训",
    description: "内部培训课程的开场介绍：背景、目标、安排与期待。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "[课程名称]", subtitle: "学完你能做到什么", note: "内训 · 2026" },
      { layout: "bullets", title: "为什么要学这个", bullets: ["业务背景：我们面临的真实挑战", "能力缺口：现在缺什么", "学了有什么用：可量化的改变"] },
      { layout: "twoColumn", title: "课程安排", columns: [{ heading: "今天的内容", bullets: ["模块 1（60 分钟）", "模块 2（60 分钟）", "演练 + Q&A（30 分钟）"] }, { heading: "学习要求", bullets: ["全程参与", "完成练习", "7 天内实践"] }] },
      { layout: "metrics", title: "学习目标", metrics: [{ label: "核心概念", value: "3 个" }, { label: "实用工具", value: "2 个" }, { label: "真实练习", value: "1 次" }] },
      { layout: "closing", title: "开始学习", subtitle: "带上你的真实问题来", note: "Let's go" },
    ],
  },
  {
    id: "knowledge-sharing",
    name: "内部知识分享",
    scenario: "知识沉淀",
    category: "教育培训",
    description: "团队内部技术或业务知识分享，适合午餐会或例会分享。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "[主题名称]", subtitle: "我学到了什么，你也可以用", note: "知识分享 · 2026" },
      { layout: "bullets", title: "背景与动机", bullets: ["为什么选这个主题", "我遇到的真实问题", "花了多久才弄清楚"] },
      { layout: "bullets", title: "核心知识点", bullets: ["关键概念 1：一句话解释", "关键概念 2：一句话解释", "关键概念 3：一句话解释"] },
      { layout: "twoColumn", title: "实战经验", columns: [{ heading: "有效的做法", bullets: ["做法 A + 效果", "做法 B + 效果"] }, { heading: "踩过的坑", bullets: ["坑 A + 教训", "坑 B + 教训"] }] },
      { layout: "closing", title: "你可以马上用的", subtitle: "一个立即可行的行动建议", note: "欢迎讨论" },
    ],
  },
  {
    id: "onboarding",
    name: "新员工入职培训",
    scenario: "入职培训",
    category: "教育培训",
    description: "新员工入职第一周的公司介绍与融入引导。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "欢迎加入 [公司名]", subtitle: "你需要知道的一切", note: "入职培训 · 2026" },
      { layout: "bullets", title: "公司是谁", bullets: ["使命：我们为什么存在", "产品：我们做什么", "客户：我们服务谁"] },
      { layout: "twoColumn", title: "文化与工作方式", columns: [{ heading: "我们的价值观", bullets: ["价值观 1", "价值观 2", "价值观 3"] }, { heading: "工作方式", bullets: ["沟通规范", "会议文化", "反馈机制"] }] },
      { layout: "timeline", title: "第一个月计划", steps: [{ label: "第 1 周", detail: "了解产品 + 认识团队" }, { label: "第 2 周", detail: "熟悉流程 + 接触客户" }, { label: "第 3–4 周", detail: "完成首个独立任务" }] },
      { layout: "bullets", title: "你的支持系统", bullets: ["直属 Leader：负责业务指导", "Buddy：日常生活问题", "HR：流程与权益"] },
      { layout: "closing", title: "我们期待你", subtitle: "带来你的视角，问出你的问题", note: "欢迎！" },
    ],
  },
  {
    id: "workshop-agenda",
    name: "工作坊 / 研讨会",
    scenario: "工作坊",
    category: "教育培训",
    description: "工作坊开场与议程介绍，激活参与者的思维与参与感。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "[工作坊主题]", subtitle: "今天我们要解决什么问题", note: "[日期] · [地点]" },
      { layout: "bullets", title: "今天的目标", bullets: ["产出目标：我们要得到什么", "过程目标：我们如何工作", "行为目标：结束后做什么"] },
      { layout: "timeline", title: "议程", steps: [{ label: "09:00–10:30", detail: "问题定义 + 现状诊断" }, { label: "10:45–12:00", detail: "方案设计 + 选择" }, { label: "13:30–15:00", detail: "行动计划 + 承诺" }] },
      { layout: "twoColumn", title: "工作规则", columns: [{ heading: "我们会做", bullets: ["积极发言", "挑战假设", "产出结论"] }, { heading: "我们不做", bullets: ["评判想法", "拖延决策", "假装同意"] }] },
      { layout: "closing", title: "开始", subtitle: "带上你的真实观点", note: "今天要有结论" },
    ],
  },
];

// ── 市场品牌 ───────────────────────────────────────────────
export const MARKETING_TEMPLATES: DeckTemplate[] = [
  {
    id: "brand-positioning",
    name: "品牌定位 / 发布",
    scenario: "品牌战略",
    category: "市场品牌",
    description: "向内部团队或外部合作方展示品牌定位与视觉体系。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "[品牌名] 品牌故事", subtitle: "我们是谁，为什么不同", note: "品牌发布 · 2026" },
      { layout: "bullets", title: "品牌定位", bullets: ["目标人群：谁在选择我们", "核心主张：我们代表什么", "品牌个性：我们的气质"] },
      { layout: "quote", quote: "[品牌核心理念一句话]", author: "品牌宣言" },
      { layout: "twoColumn", title: "品牌元素", columns: [{ heading: "视觉系统", bullets: ["主色系", "字体组合", "图形语言"] }, { heading: "声音调性", bullets: ["官方沟通语气", "内容风格", "禁忌用语"] }] },
      { layout: "closing", title: "从今天起，统一表达", subtitle: "品牌手册 / 物料中心", note: "共同守护品牌" },
    ],
  },
  {
    id: "campaign-proposal",
    name: "营销活动提案",
    scenario: "营销策划",
    category: "市场品牌",
    description: "向管理层或客户提交营销活动策划方案。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "[活动名称] 策划方案", subtitle: "目标 · 策略 · 执行计划", note: "2026" },
      { layout: "bullets", title: "活动背景与目标", bullets: ["业务背景：为什么做这次活动", "核心目标：品牌曝光 / 获客 / 转化", "KPI：具体指标"] },
      { layout: "twoColumn", title: "策略与创意", columns: [{ heading: "核心策略", bullets: ["目标人群定向", "核心信息", "差异化亮点"] }, { heading: "执行渠道", bullets: ["线上：渠道 A + B", "线下：场景 C", "私域：D"] }] },
      { layout: "timeline", title: "执行时间线", steps: [{ label: "预热期", detail: "D-14 ～ D-7" }, { label: "爆发期", detail: "D-7 ～ D0" }, { label: "沉淀期", detail: "D0 ～ D+14" }] },
      { layout: "metrics", title: "预算与预期", metrics: [{ label: "总预算", value: "¥XXX K" }, { label: "预期曝光", value: "XX 万次" }, { label: "预期转化", value: "XXX" }, { label: "CPL", value: "¥XXX" }] },
      { layout: "closing", title: "请审批", subtitle: "预算 ¥XXX K · 启动日期 [日期]", note: "期待推进" },
    ],
  },
  {
    id: "content-strategy",
    name: "内容营销策略",
    scenario: "内容营销",
    category: "市场品牌",
    description: "向团队发布内容营销策略与季度内容计划。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "内容营销策略", subtitle: "用内容建立信任，用信任驱动转化", note: "Q3 2026" },
      { layout: "bullets", title: "为什么做内容营销", bullets: ["目标受众在哪里消费内容", "内容营销 vs 广告：效率对比", "我们的内容优势"] },
      { layout: "twoColumn", title: "内容矩阵", columns: [{ heading: "平台", bullets: ["公众号：深度文章", "抖音：短视频", "LinkedIn：行业观点"] }, { heading: "内容类型", bullets: ["教育类（60%）", "案例类（30%）", "品牌类（10%）"] }] },
      { layout: "metrics", title: "Q3 内容目标", metrics: [{ label: "发布篇数", value: "XX 篇" }, { label: "目标阅读", value: "XX 万" }, { label: "线索转化", value: "XXX" }, { label: "CPL", value: "¥XXX" }] },
      { layout: "closing", title: "内容日历已就绪", subtitle: "人员分工 / 审核流程 / 发布工具", note: "开始创作" },
    ],
  },
  {
    id: "pr-crisis",
    name: "公关危机应对",
    scenario: "危机公关",
    category: "市场品牌",
    description: "向管理层汇报公关危机现状、应对措施和舆情管理计划。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "舆情应对报告", subtitle: "[事件名称] · 现状 + 策略 + 行动", note: "[日期]" },
      { layout: "bullets", title: "事件概述", bullets: ["事件发展时间线", "当前舆情热度与情绪", "主要传播渠道与核心KOL"] },
      { layout: "metrics", title: "舆情现状", metrics: [{ label: "相关内容", value: "XXX 条" }, { label: "负面占比", value: "XX%" }, { label: "预计持续", value: "X 天" }, { label: "风险等级", value: "高 / 中 / 低" }] },
      { layout: "twoColumn", title: "应对策略", columns: [{ heading: "短期（24–48 小时）", bullets: ["官方声明发布", "核心媒体沟通", "员工口径统一"] }, { heading: "中期（1–2 周）", bullets: ["正面信息补充", "KOL 背书", "持续跟进监测"] }] },
      { layout: "closing", title: "下一步行动", subtitle: "Owner / 声明草稿确认 / 媒体名单", note: "快速行动" },
    ],
  },
];

// ── 项目汇报 ───────────────────────────────────────────────
export const PROJECT_TEMPLATES: DeckTemplate[] = [
  {
    id: "project-kickoff",
    name: "项目启动会",
    scenario: "项目管理",
    category: "项目汇报",
    description: "项目启动：目标、范围、计划和团队分工。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "[项目名称] 启动", subtitle: "目标明确 · 分工清晰 · 按时交付", note: "启动会 · [日期]" },
      { layout: "bullets", title: "为什么做这个项目", bullets: ["业务背景与战略关联", "不做的代价是什么", "成功后能实现什么"] },
      { layout: "twoColumn", title: "范围 & 不做什么", columns: [{ heading: "项目范围", bullets: ["交付物 A", "交付物 B", "交付物 C"] }, { heading: "明确不做", bullets: ["超出范围 X", "超出范围 Y"] }] },
      { layout: "metrics", title: "项目概况", metrics: [{ label: "总工期", value: "X 周" }, { label: "团队规模", value: "X 人" }, { label: "总预算", value: "¥XXX K" }, { label: "优先级", value: "P0" }] },
      { layout: "timeline", title: "里程碑计划", steps: [{ label: "第 1 阶段", detail: "需求确认（2 周）" }, { label: "第 2 阶段", detail: "开发交付（6 周）" }, { label: "第 3 阶段", detail: "上线验收（2 周）" }] },
      { layout: "closing", title: "我们一起做到", subtitle: "每人明确 1 件最重要的事", note: "开始！" },
    ],
  },
  {
    id: "project-status",
    name: "项目进展汇报",
    scenario: "项目汇报",
    category: "项目汇报",
    description: "向干系人汇报项目当前状态、进展和风险。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "[项目名称] 进展汇报", subtitle: "第 X 周 · [日期]", note: "项目汇报" },
      { layout: "metrics", title: "项目健康度", metrics: [{ label: "整体进度", value: "XX%" }, { label: "预算使用", value: "XX%" }, { label: "风险等级", value: "绿 / 黄 / 红" }, { label: "剩余工期", value: "X 周" }] },
      { layout: "twoColumn", title: "本周进展", columns: [{ heading: "已完成", bullets: ["任务 A ✓", "任务 B ✓", "任务 C ✓"] }, { heading: "延期 / 阻塞", bullets: ["任务 D：原因 + 处理", "阻塞项：需要谁帮助"] }] },
      { layout: "bullets", title: "关键风险", bullets: ["风险 1：可能性 + 影响 + 应对", "风险 2：可能性 + 影响 + 应对"] },
      { layout: "closing", title: "下周计划", subtitle: "关键交付 + 需要决策的事项", note: "继续推进" },
    ],
  },
  {
    id: "project-retrospective",
    name: "项目复盘",
    scenario: "项目总结",
    category: "项目汇报",
    description: "项目结束后的全面复盘：成果、过程与经验。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "[项目名称] 复盘", subtitle: "做了什么 · 学到什么 · 下次如何", note: "项目总结 · 2026" },
      { layout: "metrics", title: "项目成果", metrics: [{ label: "完成率", value: "XX%" }, { label: "时间", value: "准时 / 延期 X 周" }, { label: "预算", value: "结余 / 超支 XX%" }, { label: "满意度", value: "X.X/5" }] },
      { layout: "twoColumn", title: "做得好的", columns: [{ heading: "成功因素", bullets: ["因素 1", "因素 2", "因素 3"] }, { heading: "值得固化的", bullets: ["实践 A", "实践 B"] }] },
      { layout: "twoColumn", title: "可以做得更好", columns: [{ heading: "主要问题", bullets: ["问题 1：根本原因", "问题 2：根本原因"] }, { heading: "改进措施", bullets: ["措施 A（Owner）", "措施 B（Owner）"] }] },
      { layout: "closing", title: "经验沉淀", subtitle: "把这次的学习写入工作手册", note: "每次复盘让我们更好" },
    ],
  },
  {
    id: "research-report",
    name: "调研报告发布",
    scenario: "调研报告",
    category: "项目汇报",
    description: "向内部或客户呈现用户调研 / 市场调研的核心发现。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "[调研主题] 研究报告", subtitle: "数据说话，洞察驱动决策", note: "调研 · 2026" },
      { layout: "bullets", title: "研究设计", bullets: ["调研目的：回答什么核心问题", "方法：问卷 X 份 + 深访 X 人", "时间：[时间段]"] },
      { layout: "metrics", title: "样本概况", metrics: [{ label: "有效样本", value: "XXX 份" }, { label: "回收率", value: "XX%" }, { label: "样本范围", value: "XX 城市" }] },
      { layout: "bullets", title: "三个核心发现", bullets: ["发现 1：数据 + 解读 + 影响", "发现 2：数据 + 解读 + 影响", "发现 3：数据 + 解读 + 影响"] },
      { layout: "twoColumn", title: "行动建议", columns: [{ heading: "产品方向", bullets: ["建议 A", "建议 B"] }, { heading: "运营方向", bullets: ["建议 C", "建议 D"] }] },
      { layout: "closing", title: "数据不撒谎", subtitle: "根据洞察制定行动计划", note: "期待讨论" },
    ],
  },
];

// ── 客户成功 ───────────────────────────────────────────────
export const CUSTOMER_SUCCESS_TEMPLATES: DeckTemplate[] = [
  {
    id: "qbr-review",
    name: "QBR 季度业务回顾",
    scenario: "客户 QBR",
    category: "客户成功",
    description: "与客户共同进行季度业务回顾，确认价值和下阶段规划。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "Q X 业务回顾", subtitle: "[客户名] · 季度共创", note: "QBR · 2026" },
      { layout: "metrics", title: "本季使用数据", metrics: [{ label: "活跃用户", value: "XXX" }, { label: "功能使用率", value: "XX%" }, { label: "响应时长", value: "< X 小时" }, { label: "满意度", value: "X.X/5" }] },
      { layout: "twoColumn", title: "已实现的价值", columns: [{ heading: "量化成果", bullets: ["节省时间 XX 小时/周", "错误率降低 XX%", "成本节省 ¥XXX K"] }, { heading: "非量化成果", bullets: ["团队能力提升", "流程标准化", "风险降低"] }] },
      { layout: "bullets", title: "未充分使用的功能", bullets: ["功能 A：使用率仅 XX%，可以帮你做 XXX", "功能 B：尚未开通，适用于 XXX 场景", "建议：下季度重点试用 XXX"] },
      { layout: "timeline", title: "下季度规划", steps: [{ label: "M1", detail: "功能 A 深度上线" }, { label: "M2", detail: "团队培训 + 扩大使用" }, { label: "M3", detail: "效果评估 + 续约准备" }] },
      { layout: "closing", title: "下季度共同目标", subtitle: "确认 1–2 个合作重点", note: "感谢信任" },
    ],
  },
  {
    id: "onboarding-plan",
    name: "客户上线计划",
    scenario: "客户上线",
    category: "客户成功",
    description: "客户签约后的上线启动计划，明确里程碑与双方责任。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "上线实施计划", subtitle: "[客户名] · 从签约到成功上线", note: "实施启动 · 2026" },
      { layout: "bullets", title: "上线目标", bullets: ["业务目标：达成什么效果", "技术目标：系统稳定运行", "时间目标：X 周内全量上线"] },
      { layout: "twoColumn", title: "双方职责", columns: [{ heading: "我们负责", bullets: ["系统配置", "数据导入", "培训交付"] }, { heading: "客户负责", bullets: ["内部协调人", "数据提供", "测试验收"] }] },
      { layout: "timeline", title: "上线节奏", steps: [{ label: "第 1 周", detail: "环境配置 + 需求确认" }, { label: "第 2–3 周", detail: "数据迁移 + 培训" }, { label: "第 4 周", detail: "试运行 + 验收" }] },
      { layout: "closing", title: "我们一起做到", subtitle: "第一个里程碑：[日期] 完成配置", note: "期待合作" },
    ],
  },
  {
    id: "churn-recovery",
    name: "客户挽留方案",
    scenario: "流失预警",
    category: "客户成功",
    description: "针对流失风险客户，展示改进措施和挽留方案。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "合作改进方案", subtitle: "正视问题，重建信任", note: "专项沟通 · 2026" },
      { layout: "bullets", title: "我们听到了你的问题", bullets: ["问题 1：具体描述", "问题 2：具体描述", "我们的态度：负责任地解决"] },
      { layout: "twoColumn", title: "改进承诺", columns: [{ heading: "已完成", bullets: ["措施 A（已验证）", "措施 B（已验证）"] }, { heading: "计划中", bullets: ["措施 C（X 周内）", "措施 D（X 周内）"] }] },
      { layout: "metrics", title: "改进后效果", metrics: [{ label: "响应时间", value: "< X 小时" }, { label: "问题解决率", value: "XX%" }, { label: "稳定性", value: "99.X%" }] },
      { layout: "closing", title: "给我们一个证明的机会", subtitle: "30 天观察期 + 专属支持", note: "感谢你的坦诚" },
    ],
  },
  {
    id: "success-case",
    name: "客户成功案例展示",
    scenario: "案例分享",
    category: "客户成功",
    description: "向潜在客户展示标杆客户的成功故事，增强信任。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "[客户名] 成功案例", subtitle: "从 [问题] 到 [成果] 的转变", note: "案例分享 · 2026" },
      { layout: "bullets", title: "客户背景", bullets: ["公司规模与行业", "在我们接触前面临的挑战", "为什么选择我们"] },
      { layout: "metrics", title: "实现的成果", metrics: [{ label: "效率提升", value: "+XX%" }, { label: "成本节省", value: "¥XXX K/年" }, { label: "上线周期", value: "X 周" }, { label: "用户满意度", value: "X.X/5" }] },
      { layout: "quote", quote: "[客户评价原话]", author: "[客户姓名] · [职位] · [公司]" },
      { layout: "closing", title: "你也可以", subtitle: "了解我们如何为你定制方案", note: "联系我们" },
    ],
  },
];

// ── 技术架构 ───────────────────────────────────────────────
export const TECH_TEMPLATES: DeckTemplate[] = [
  {
    id: "tech-architecture",
    name: "技术架构评审",
    scenario: "架构设计",
    category: "技术架构",
    description: "向技术团队或管理层展示系统架构设计与技术选型。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "[系统名称] 架构设计", subtitle: "设计目标 · 方案 · 权衡", note: "技术评审 · 2026" },
      { layout: "bullets", title: "设计目标与约束", bullets: ["功能需求：必须实现什么", "非功能需求：性能 / 可用性 / 扩展性", "约束：技术栈 / 时间 / 预算"] },
      { layout: "twoColumn", title: "架构方案", columns: [{ heading: "核心组件", bullets: ["组件 A：职责描述", "组件 B：职责描述", "组件 C：职责描述"] }, { heading: "数据流", bullets: ["请求路径", "数据存储策略", "缓存层设计"] }] },
      { layout: "metrics", title: "性能目标", metrics: [{ label: "QPS", value: "XXXK" }, { label: "P99 延迟", value: "< XXms" }, { label: "可用性", value: "99.99%" }, { label: "存储", value: "XXX TB" }] },
      { layout: "twoColumn", title: "技术选型", columns: [{ heading: "选择了", bullets: ["技术 A：理由", "技术 B：理由"] }, { heading: "放弃了", bullets: ["备选 X：原因", "备选 Y：原因"] }] },
      { layout: "closing", title: "评审问题", subtitle: "请重点关注 XXX 的权衡选择", note: "期待讨论" },
    ],
  },
  {
    id: "incident-review",
    name: "线上故障复盘",
    scenario: "故障复盘",
    category: "技术架构",
    description: "故障发生后的 Post-mortem 复盘报告，无责问责。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "故障复盘报告", subtitle: "[事件名称] · 时间线 · 原因 · 改进", note: "Post-mortem · [日期]" },
      { layout: "metrics", title: "故障概况", metrics: [{ label: "影响时长", value: "X 小时" }, { label: "影响用户", value: "XX%" }, { label: "严重等级", value: "P0 / P1" }, { label: "发现方式", value: "监控 / 用户反馈" }] },
      { layout: "timeline", title: "事件时间线", steps: [{ label: "发生", detail: "XX:XX 异常触发" }, { label: "发现", detail: "XX:XX 报警 / 发现" }, { label: "恢复", detail: "XX:XX 服务恢复" }] },
      { layout: "bullets", title: "根本原因", bullets: ["直接原因：触发故障的具体操作 / 代码", "根本原因：系统设计 / 流程缺陷", "诱发因素：上线变更 / 流量突增等"] },
      { layout: "twoColumn", title: "改进措施", columns: [{ heading: "短期（1 周内）", bullets: ["修复 A", "修复 B"] }, { heading: "长期（1 个月内）", bullets: ["架构改进 C", "监控增强 D"] }] },
      { layout: "closing", title: "防止复发", subtitle: "责任人 / 截止时间 / 验收标准", note: "无责复盘，共同提高" },
    ],
  },
  {
    id: "tech-roadmap",
    name: "技术规划 / 技术债",
    scenario: "技术管理",
    category: "技术架构",
    description: "向管理层或产品团队展示技术规划与技术债处理优先级。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "技术规划 2026–2027", subtitle: "构建可持续的技术基础", note: "技术团队" },
      { layout: "bullets", title: "技术现状", bullets: ["架构优势：哪些是坚实的基础", "技术债：当前最大的隐患", "资源现状：人力与时间约束"] },
      { layout: "twoColumn", title: "技术债优先级", columns: [{ heading: "必须解决（影响业务）", bullets: ["债务 A：风险描述", "债务 B：风险描述"] }, { heading: "计划优化（提升效率）", bullets: ["债务 C：效率损耗", "债务 D：可延后"] }] },
      { layout: "timeline", title: "技术投资路线图", steps: [{ label: "Q3", detail: "还债优先：基础稳定性" }, { label: "Q4", detail: "平台化：提升开发效率" }, { label: "2027", detail: "创新：新技术探索" }] },
      { layout: "metrics", title: "预期收益", metrics: [{ label: "开发提速", value: "+XX%" }, { label: "故障减少", value: "XX%" }, { label: "部署频率", value: "X 次/天" }] },
      { layout: "closing", title: "技术是业务的基础", subtitle: "申请 XX% 时间投入技术改进", note: "持续演进" },
    ],
  },
  {
    id: "security-review",
    name: "安全与合规汇报",
    scenario: "安全合规",
    category: "技术架构",
    description: "向管理层或审计机构汇报安全现状、风险与合规状态。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "信息安全年度报告", subtitle: "风险现状 · 合规进展 · 提升计划", note: "2026" },
      { layout: "metrics", title: "安全现状", metrics: [{ label: "漏洞修复率", value: "XX%" }, { label: "安全事件", value: "X 起" }, { label: "合规达标率", value: "XX%" }, { label: "覆盖资产", value: "XXX 台" }] },
      { layout: "twoColumn", title: "主要风险", columns: [{ heading: "已识别风险", bullets: ["风险 A：等级 + 描述", "风险 B：等级 + 描述"] }, { heading: "应对措施", bullets: ["措施 A（完成率）", "措施 B（完成率）"] }] },
      { layout: "bullets", title: "合规进展", bullets: ["ISO 27001：认证状态", "等保三级：进展说明", "GDPR / 数据合规：执行情况"] },
      { layout: "closing", title: "下年度投入申请", subtitle: "预算 ¥XXX K · 核心改进项", note: "安全是底线" },
    ],
  },
];

// ── 创业初期 ───────────────────────────────────────────────
export const STARTUP_TEMPLATES: DeckTemplate[] = [
  {
    id: "business-plan",
    name: "商业计划书",
    scenario: "创业计划",
    category: "创业初期",
    description: "全面的创业商业计划，适合早期团队内部对齐或提交给孵化器。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "[项目名] 商业计划", subtitle: "问题 · 方案 · 市场 · 团队", note: "2026" },
      { layout: "bullets", title: "我们要解决的问题", bullets: ["问题描述：具体场景", "现有方案的缺陷", "问题规模有多大"] },
      { layout: "bullets", title: "我们的解决方案", bullets: ["产品核心功能", "使用方式与用户体验", "为什么比现有方案更好"] },
      { layout: "metrics", title: "市场规模", metrics: [{ label: "TAM", value: "¥XXB" }, { label: "SAM", value: "¥XXM" }, { label: "SOM (Year 3)", value: "¥XXM" }] },
      { layout: "twoColumn", title: "商业模式", columns: [{ heading: "收入来源", bullets: ["主要变现方式", "ARPU 预估", "定价策略"] }, { heading: "成本结构", bullets: ["主要成本项", "规模经济预期", "盈利时间线"] }] },
      { layout: "bullets", title: "团队", bullets: ["创始人：背景与核心优势", "联创 / 核心成员：互补能力", "顾问 / 投资人背书"] },
      { layout: "closing", title: "我们需要什么", subtitle: "融资 ¥XXX 万 / 资源 / 合作", note: "期待你的支持" },
    ],
  },
  {
    id: "mvp-validation",
    name: "MVP 验证汇报",
    scenario: "早期验证",
    category: "创业初期",
    description: "向投资人或顾问汇报 MVP 验证结果与迭代方向。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "MVP 验证报告", subtitle: "我们验证了什么，学到了什么", note: "2026" },
      { layout: "bullets", title: "验证假设", bullets: ["假设 1：用户有这个问题", "假设 2：用户愿意为解法付费", "假设 3：我们能以 ¥XXX 成本获客"] },
      { layout: "metrics", title: "验证数据", metrics: [{ label: "接触用户", value: "XXX" }, { label: "付费用户", value: "XX" }, { label: "留存率", value: "XX%" }, { label: "NPS", value: "XX" }] },
      { layout: "twoColumn", title: "发现与洞察", columns: [{ heading: "验证了", bullets: ["假设 A ✓ + 证据", "假设 B ✓ + 证据"] }, { heading: "推翻了", bullets: ["假设 C ✗ + 原因", "调整方向"] }] },
      { layout: "bullets", title: "下一步迭代", bullets: ["继续：保留有效的", "改变：调整未验证的", "停止：放弃不成立的"] },
      { layout: "closing", title: "我们找到了方向", subtitle: "下 90 天目标", note: "持续学习" },
    ],
  },
  {
    id: "co-founder-pitch",
    name: "联合创始人招募",
    scenario: "联创招募",
    category: "创业初期",
    description: "向潜在联合创始人展示项目机会，建立共识。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "一起做一件大事", subtitle: "[项目名] · 我们在寻找联合创始人", note: "2026" },
      { layout: "bullets", title: "我们在做什么", bullets: ["问题：真实存在的大机会", "解法：我们的独特切入点", "进展：已经做到了什么"] },
      { layout: "twoColumn", title: "我们的优势", columns: [{ heading: "已有的", bullets: ["早期用户 / 数据", "领域 Know-how", "资源积累"] }, { heading: "缺少的", bullets: ["你能带来的能力", "你能填补的空白"] }] },
      { layout: "bullets", title: "我们在寻找", bullets: ["核心能力：XXX（技术 / 产品 / 商务）", "价值观：XXX", "背景：XXX"] },
      { layout: "closing", title: "先喝杯咖啡", subtitle: "联系方式", note: "等你" },
    ],
  },
  {
    id: "startup-weekly",
    name: "早期团队周会",
    scenario: "创业团队管理",
    category: "创业初期",
    description: "创业初期团队周会，对齐重点、发现问题、共同决策。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "周会", subtitle: "第 XX 周 · 做了什么 / 学到了什么", note: "[日期]" },
      { layout: "metrics", title: "本周关键数字", metrics: [{ label: "新增用户", value: "XX" }, { label: "收入", value: "¥XXX" }, { label: "沟通客户", value: "XX" }, { label: "完成功能", value: "X 个" }] },
      { layout: "twoColumn", title: "进展 & 阻塞", columns: [{ heading: "推进了", bullets: ["事项 A ✓", "事项 B ✓"] }, { heading: "卡住了", bullets: ["事项 C：原因", "需要讨论的决策"] }] },
      { layout: "bullets", title: "本周最重要的学习", bullets: ["用户反馈中最意外的发现", "一个被推翻的假设", "一个新的机会信号"] },
      { layout: "closing", title: "下周 1 件最重要的事", subtitle: "[具体事项 + Owner]", note: "继续冲" },
    ],
  },
];

// ── 年度总结 ───────────────────────────────────────────────
export const ANNUAL_TEMPLATES: DeckTemplate[] = [
  {
    id: "annual-review",
    name: "年度工作总结",
    scenario: "年度总结",
    category: "年度总结",
    description: "个人或部门年度工作汇报：成果、成长与下年度计划。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "2026 年度工作总结", subtitle: "[姓名 / 部门] · 回顾与展望", note: "年终汇报" },
      { layout: "metrics", title: "年度核心成果", metrics: [{ label: "完成目标", value: "XX 项" }, { label: "达成率", value: "XX%" }, { label: "超额亮点", value: "X 项" }, { label: "参与项目", value: "X 个" }] },
      { layout: "bullets", title: "最重要的 3 件事", bullets: ["成果 1：背景 + 结果 + 影响", "成果 2：背景 + 结果 + 影响", "成果 3：背景 + 结果 + 影响"] },
      { layout: "twoColumn", title: "成长与不足", columns: [{ heading: "今年的成长", bullets: ["能力提升 A", "能力提升 B", "认知突破 C"] }, { heading: "需要改进", bullets: ["不足 A + 原因", "不足 B + 改进计划"] }] },
      { layout: "bullets", title: "2027 年计划", bullets: ["核心目标：具体 + 可衡量", "能力发展方向", "期望的支持与资源"] },
      { layout: "closing", title: "期待 2027", subtitle: "感谢团队的支持与协作", note: "谢谢" },
    ],
  },
  {
    id: "company-annual",
    name: "公司年度发布",
    scenario: "公司年会",
    category: "年度总结",
    description: "公司年会上的年度回顾与新年展望，鼓舞士气、对齐方向。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "[公司名] 2026 年度发布", subtitle: "这一年，我们一起做到了", note: "年会 · 2026" },
      { layout: "metrics", title: "2026 核心成就", metrics: [{ label: "营收", value: "¥XXM" }, { label: "增速", value: "+XX%" }, { label: "客户数", value: "X,XXX" }, { label: "团队规模", value: "XXX 人" }] },
      { layout: "bullets", title: "这一年最骄傲的事", bullets: ["成就 1：故事 + 数字", "成就 2：故事 + 数字", "成就 3：故事 + 数字"] },
      { layout: "quote", quote: "[创始人 / CEO 寄语]", author: "[姓名] · [职位]" },
      { layout: "bullets", title: "2027 最重要的目标", bullets: ["目标 1：为什么重要 + 如何衡量", "目标 2：为什么重要 + 如何衡量", "目标 3：为什么重要 + 如何衡量"] },
      { layout: "closing", title: "2027，一起向前", subtitle: "感谢每一位团队成员", note: "新年快乐" },
    ],
  },
  {
    id: "department-annual",
    name: "部门年度汇报",
    scenario: "部门总结",
    category: "年度总结",
    description: "部门向公司管理层汇报全年成果与下年度计划。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "[部门名] 年度汇报", subtitle: "2026 成果 · 2027 计划", note: "管理层汇报" },
      { layout: "metrics", title: "全年核心指标", metrics: [{ label: "KPI 达成率", value: "XX%" }, { label: "超额完成", value: "X 项" }, { label: "预算执行率", value: "XX%" }, { label: "团队规模", value: "XX 人" }] },
      { layout: "twoColumn", title: "年度核心贡献", columns: [{ heading: "业务贡献", bullets: ["项目 A：业务价值", "项目 B：业务价值"] }, { heading: "能力建设", bullets: ["建立了 XX 流程", "沉淀了 XX 方法论"] }] },
      { layout: "bullets", title: "经验与教训", bullets: ["最值得复制的成功经验", "最值得避免的失误教训", "团队能力的最大成长点"] },
      { layout: "metrics", title: "2027 目标", metrics: [{ label: "KPI 1", value: "目标值" }, { label: "KPI 2", value: "目标值" }, { label: "新增能力", value: "X 项" }, { label: "预算申请", value: "¥XXM" }] },
      { layout: "closing", title: "期待支持", subtitle: "预算 / 编制 / 资源需求", note: "感谢" },
    ],
  },
  {
    id: "investor-annual",
    name: "年度投资人报告",
    scenario: "年度投资人更新",
    category: "年度总结",
    description: "向投资人发送年度经营报告，全面回顾和前瞻。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "2026 年度报告", subtitle: "[公司名] · 全年回顾与 2027 展望", note: "机密 · 投资人版" },
      { layout: "metrics", title: "2026 年度关键指标", metrics: [{ label: "ARR", value: "¥XXM" }, { label: "YoY", value: "+XX%" }, { label: "客户留存", value: "XX%" }, { label: "现金储备", value: "¥XXM" }] },
      { layout: "twoColumn", title: "完成了什么", columns: [{ heading: "超预期", bullets: ["目标 A：实际 vs 计划", "目标 B：实际 vs 计划"] }, { heading: "未达预期", bullets: ["目标 C：差距 + 原因", "目标 D：调整说明"] }] },
      { layout: "bullets", title: "战略进展", bullets: ["战略重点 1 的关键进展", "战略重点 2 的关键进展", "市场格局变化及我们的应对"] },
      { layout: "metrics", title: "2027 展望", metrics: [{ label: "ARR 目标", value: "¥XXXM" }, { label: "增速", value: "+XX%" }, { label: "预算", value: "¥XXM" }, { label: "关键里程碑", value: "X 个" }] },
      { layout: "closing", title: "感谢 2026", subtitle: "期待 2027 年继续同行", note: "感谢支持" },
    ],
  },
];
