import type { DeckTemplate } from "../types";

export const PRODUCT_TEMPLATES: DeckTemplate[] = [
  {
    id: "product-launch",
    name: "产品发布",
    scenario: "产品发布",
    category: "产品发布",
    description: "新产品 / 大版本对内外发布，7 页标准结构。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "全新 [产品名]", subtitle: "一句话说清它为用户带来什么", note: "发布 · 2026" },
      { layout: "section", title: "01", subtitle: "我们要解决的问题" },
      { layout: "bullets", title: "三大新能力", bullets: ["能力一：更快", "能力二：更省", "能力三：更稳"] },
      { layout: "twoColumn", title: "之前 vs 现在", columns: [{ heading: "之前", bullets: ["手动、易错", "割裂体验"] }, { heading: "现在", bullets: ["自动、可靠", "一体化"] }] },
      { layout: "metrics", title: "早期数据", metrics: [{ label: "提速", value: "3×" }, { label: "采用", value: "68%" }, { label: "满意", value: "4.7/5" }] },
      { layout: "timeline", title: "发布节奏", steps: [{ label: "今天", detail: "灰度开放" }, { label: "下周", detail: "全量上线" }, { label: "下月", detail: "生态集成" }] },
      { layout: "closing", title: "现在就试用", subtitle: "入口 / 文档 / 反馈渠道", note: "Let's ship" },
    ],
  },
  {
    id: "product-roadmap",
    name: "产品路线图发布",
    scenario: "产品规划",
    category: "产品发布",
    description: "向内部团队或外部客户展示产品未来规划与优先级。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "[产品名] 路线图", subtitle: "2026–2027 产品方向与优先级", note: "产品团队" },
      { layout: "bullets", title: "产品愿景", bullets: ["我们要成为什么", "解决谁的哪些问题", "3 年后的产品形态"] },
      { layout: "twoColumn", title: "现在 vs 未来", columns: [{ heading: "当前能力", bullets: ["核心模块 A", "核心模块 B", "集成能力"] }, { heading: "计划建设", bullets: ["能力 X（Q3）", "能力 Y（Q4）", "能力 Z（2027）"] }] },
      { layout: "timeline", title: "2026 H2 路线图", steps: [{ label: "Q3", detail: "功能 A + B 发布" }, { label: "Q4", detail: "功能 C + 平台开放" }, { label: "2027 Q1", detail: "生态 + 国际化" }] },
      { layout: "bullets", title: "优先级决策原则", bullets: ["用户价值：解决多少人的多大痛", "战略契合：与公司目标的关联度", "可行性：技术复杂度与交付把握"] },
      { layout: "closing", title: "期待共创", subtitle: "欢迎反馈与建议", note: "Let's build together" },
    ],
  },
  {
    id: "feature-review",
    name: "功能迭代回顾",
    scenario: "产品迭代",
    category: "产品发布",
    description: "内部产品迭代复盘：已上线功能效果、问题与下版本方向。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "产品迭代复盘", subtitle: "版本 X.X · 上线效果与学习", note: "产品团队内部" },
      { layout: "metrics", title: "版本上线数据", metrics: [{ label: "使用率", value: "XX%" }, { label: "满意度", value: "X.X/5" }, { label: "Bug 数", value: "X" }, { label: "完成功能", value: "X 项" }] },
      { layout: "twoColumn", title: "功能效果", columns: [{ heading: "符合预期", bullets: ["功能 A：数据验证", "功能 B：用户正反馈"] }, { heading: "低于预期", bullets: ["功能 C：原因分析", "功能 D：后续方案"] }] },
      { layout: "bullets", title: "关键学习", bullets: ["用户行为与预期的最大偏差", "工程交付中的主要摩擦点", "下次迭代可改进的流程"] },
      { layout: "closing", title: "下版本方向", subtitle: "聚焦 X 个核心改进点", note: "持续迭代" },
    ],
  },
  {
    id: "beta-launch",
    name: "Beta 测试启动",
    scenario: "产品测试",
    category: "产品发布",
    description: "向 Beta 用户介绍产品、使用方法和反馈渠道。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "欢迎加入 Beta 测试", subtitle: "[产品名] · 你是最早体验者", note: "Beta · 2026" },
      { layout: "bullets", title: "你将体验什么", bullets: ["核心功能 A：解决 XXX 问题", "核心功能 B：让 XXX 更简单", "核心功能 C：全新的 XXX 体验"] },
      { layout: "twoColumn", title: "如何开始", columns: [{ heading: "快速上手", bullets: ["第 1 步：注册账号", "第 2 步：完成引导", "第 3 步：开始使用"] }, { heading: "我们需要你", bullets: ["真实使用并反馈", "填写每周问卷", "加入用户群"] }] },
      { layout: "bullets", title: "已知限制（Beta 版）", bullets: ["功能 X 尚未完善，预计 XX 月发布", "数据仅保留 30 天", "暂不支持 XXX"] },
      { layout: "closing", title: "感谢你的参与", subtitle: "反馈渠道 / 联系方式", note: "你的反馈将改变产品" },
    ],
  },
  {
    id: "api-launch",
    name: "API / 开发者平台发布",
    scenario: "开发者生态",
    category: "产品发布",
    description: "向开发者展示开放平台能力、文档和接入方式。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "[产品名] 开放平台", subtitle: "把能力开放给每个开发者", note: "Developer · 2026" },
      { layout: "bullets", title: "开放了什么", bullets: ["API 能力清单（核心 3–5 个）", "Webhook / 事件推送", "SDK 支持语言"] },
      { layout: "twoColumn", title: "核心优势", columns: [{ heading: "技术", bullets: ["99.99% SLA", "< 100ms 响应", "完善文档"] }, { heading: "商业", bullets: ["免费额度 X 万次/月", "按量付费", "企业版定制"] }] },
      { layout: "metrics", title: "平台数据", metrics: [{ label: "注册开发者", value: "XXXX" }, { label: "日调用量", value: "XX 万次" }, { label: "集成应用", value: "XXX" }, { label: "文档覆盖", value: "100%" }] },
      { layout: "timeline", title: "接入路径", steps: [{ label: "注册", detail: "5 分钟获取 API Key" }, { label: "接入", detail: "Hello World 示例" }, { label: "上线", detail: "联系商务获支持" }] },
      { layout: "closing", title: "开始构建", subtitle: "文档 / 社区 / 联系我们", note: "Build with us" },
    ],
  },
  {
    id: "product-strategy",
    name: "产品战略规划",
    scenario: "产品战略",
    category: "产品发布",
    description: "面向高管团队的产品战略方向对齐，含市场、定位和长期目标。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "[产品名] 战略规划", subtitle: "2026–2028 产品方向", note: "高管对齐" },
      { layout: "bullets", title: "市场判断", bullets: ["市场趋势：3 个正在发生的重大变化", "用户需求演变：从 XXX 到 XXX", "竞争格局：空白机会在哪里"] },
      { layout: "twoColumn", title: "战略选择", columns: [{ heading: "聚焦（做）", bullets: ["核心用户群 A", "高价值场景 B", "差异化功能 C"] }, { heading: "放弃（不做）", bullets: ["低价值长尾需求", "竞品已有优势的领域", "资源分散的方向"] }] },
      { layout: "metrics", title: "目标", metrics: [{ label: "2026 用户", value: "XX 万" }, { label: "2027 用户", value: "XX 万" }, { label: "市占率", value: "XX%" }, { label: "NPS", value: "≥ XX" }] },
      { layout: "timeline", title: "战略执行路径", steps: [{ label: "2026", detail: "打赢核心战场" }, { label: "2027", detail: "扩展相邻市场" }, { label: "2028", detail: "平台化 / 生态" }] },
      { layout: "closing", title: "我们的押注", subtitle: "一句话总结战略核心", note: "期待讨论" },
    ],
  },
  {
    id: "design-review",
    name: "产品设计评审",
    scenario: "设计评审",
    category: "产品发布",
    description: "向团队展示新功能设计方案，收集反馈并对齐。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "[功能名] 设计方案", subtitle: "解决问题 · 设计逻辑 · 方案选择", note: "设计评审 · 2026" },
      { layout: "bullets", title: "我们要解决什么", bullets: ["用户痛点：描述具体场景", "现有方案的缺陷", "本次设计的目标"] },
      { layout: "twoColumn", title: "设计方案对比", columns: [{ heading: "方案 A", bullets: ["优点 1", "优点 2", "缺点：XXX"] }, { heading: "方案 B（推荐）", bullets: ["优点 1", "优点 2", "权衡：XXX"] }] },
      { layout: "bullets", title: "推荐方案说明", bullets: ["核心交互逻辑", "关键设计决策与原因", "边界 case 处理"] },
      { layout: "bullets", title: "需要确认的问题", bullets: ["技术可行性确认", "数据 / 权限需求", "灰度策略"] },
      { layout: "closing", title: "请给出反馈", subtitle: "截止 [日期] 收集意见", note: "感谢参与" },
    ],
  },
];
