import type { DeckTemplate } from "../types";

export const SALES_TEMPLATES: DeckTemplate[] = [
  {
    id: "sales-proposal",
    name: "B2B 销售提案",
    scenario: "销售提案",
    category: "销售提案",
    description: "面向客户的价值主张与方案提案，7 页经典结构。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "致 [客户名] 的合作方案", subtitle: "用 [产品] 解决 [关键问题]", note: "提案 · 2026" },
      { layout: "bullets", title: "我们对你现状的理解", bullets: ["你正面临的挑战", "它对业务的代价", "你期望达到的结果"] },
      { layout: "twoColumn", title: "方案概览", columns: [{ heading: "我们提供", bullets: ["核心模块 A", "核心模块 B", "实施与培训"] }, { heading: "你将获得", bullets: ["效率提升", "成本下降", "可量化结果"] }] },
      { layout: "timeline", title: "落地路径", steps: [{ label: "第 1 周", detail: "对齐与配置" }, { label: "第 2–4 周", detail: "试点上线" }, { label: "第 5 周+", detail: "全量推广" }] },
      { layout: "metrics", title: "预期 ROI", metrics: [{ label: "效率", value: "+30%" }, { label: "成本", value: "-18%" }, { label: "回本", value: "4 个月" }, { label: "NPS", value: "+20" }] },
      { layout: "quote", quote: "我们只为可验证的结果负责，而不是功能清单。", author: "你的团队" },
      { layout: "closing", title: "下一步", subtitle: "确认试点范围 · 启动时间", note: "期待合作" },
    ],
  },
  {
    id: "saas-renewal",
    name: "SaaS 续约 / 增购提案",
    scenario: "客户续约",
    category: "销售提案",
    description: "向现有客户展示已交付价值并推动续约或扩量。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "[客户名] 年度复盘", subtitle: "我们一起创造的价值", note: "续约提案 · 2026" },
      { layout: "metrics", title: "本年度交付成果", metrics: [{ label: "效率提升", value: "+XX%" }, { label: "节省成本", value: "¥XXX K" }, { label: "活跃用户", value: "XXX" }, { label: "满意度", value: "X.X/5" }] },
      { layout: "bullets", title: "核心使用亮点", bullets: ["使用最频繁的功能 TOP 3", "已解决的关键业务问题", "用户反馈中的正面评价"] },
      { layout: "twoColumn", title: "续约方案", columns: [{ heading: "标准续约", bullets: ["原有席位", "价格持平", "标准支持"] }, { heading: "增购方案", bullets: ["新增席位 / 模块", "X 折优惠", "专属 CSM"] }] },
      { layout: "bullets", title: "新一年规划", bullets: ["客户下年度核心目标", "我们的支持计划", "共创路线图"] },
      { layout: "closing", title: "继续前行", subtitle: "续约确认 · 合同签署", note: "感谢信任" },
    ],
  },
  {
    id: "enterprise-solution",
    name: "大客户解决方案",
    scenario: "企业级销售",
    category: "销售提案",
    description: "针对集团 / 大企业的复杂解决方案提案，含实施与集成规划。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "[解决方案名称]", subtitle: "为 [客户] 量身定制的数字化升级", note: "企业方案 · 2026" },
      { layout: "bullets", title: "对贵方现状的理解", bullets: ["核心痛点 1", "核心痛点 2", "期望达成的业务目标"] },
      { layout: "twoColumn", title: "方案架构", columns: [{ heading: "模块组成", bullets: ["模块 A：功能描述", "模块 B：功能描述", "模块 C：集成层"] }, { heading: "交付内容", bullets: ["系统部署 + 配置", "数据迁移", "培训 + 文档"] }] },
      { layout: "metrics", title: "预期价值", metrics: [{ label: "效率", value: "+XX%" }, { label: "成本节省", value: "¥XXM/年" }, { label: "回本周期", value: "X 个月" }, { label: "风险降低", value: "XX%" }] },
      { layout: "timeline", title: "实施计划", steps: [{ label: "第 1 阶段", detail: "需求确认 + 方案设计（4 周）" }, { label: "第 2 阶段", detail: "开发 + 集成（8 周）" }, { label: "第 3 阶段", detail: "测试 + 上线（4 周）" }] },
      { layout: "twoColumn", title: "服务承诺", columns: [{ heading: "SLA", bullets: ["99.9% 可用性", "4 小时响应", "年度优化迭代"] }, { heading: "团队", bullets: ["专属项目经理", "7×12 技术支持", "季度 QBR"] }] },
      { layout: "closing", title: "开启合作", subtitle: "下一步：POC 范围确认", note: "期待深度合作" },
    ],
  },
  {
    id: "competitive-displacement",
    name: "竞品替换提案",
    scenario: "竞争替换",
    category: "销售提案",
    description: "帮助客户从竞品迁移，降低迁移成本感知，展示迁移成效。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "为什么现在是切换的最好时机", subtitle: "从 [竞品] 到 [产品名] 的迁移方案", note: "2026" },
      { layout: "twoColumn", title: "你目前遇到的问题", columns: [{ heading: "现有方案的痛点", bullets: ["价格持续上涨", "功能迟迟不更新", "数据锁定风险"] }, { heading: "你真正需要的", bullets: ["灵活配置", "持续创新", "数据自主"] }] },
      { layout: "bullets", title: "我们的差异", bullets: ["功能对比：我们领先的 3 个关键维度", "价格：同等能力节省 XX%", "迁移：提供全程托管迁移服务"] },
      { layout: "timeline", title: "迁移路径（零停机）", steps: [{ label: "第 1 周", detail: "数据导出 + 账号配置" }, { label: "第 2–3 周", detail: "并行运行 + 验证" }, { label: "第 4 周", detail: "完全切换 + 旧系统下线" }] },
      { layout: "metrics", title: "客户迁移成效", metrics: [{ label: "迁移客户", value: "XXX 家" }, { label: "平均迁移周期", value: "X 周" }, { label: "迁移后留存", value: "XX%" }, { label: "满意度", value: "X.X/5" }] },
      { layout: "closing", title: "今天开始，X 周完成切换", subtitle: "联系我们安排技术评估", note: "期待合作" },
    ],
  },
  {
    id: "channel-partner",
    name: "渠道 / 代理商招募",
    scenario: "渠道合作",
    category: "销售提案",
    description: "向潜在渠道合作伙伴展示合作价值与政策。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "与 [公司名] 共同成长", subtitle: "渠道合作伙伴计划", note: "2026" },
      { layout: "bullets", title: "我们是谁", bullets: ["产品定位与核心价值主张", "已服务 XXX 家客户", "行业领先的 NPS XX"] },
      { layout: "twoColumn", title: "合作政策", columns: [{ heading: "你的收益", bullets: ["XX% 佣金", "返点奖励", "品牌背书"] }, { heading: "我们的支持", bullets: ["销售培训", "市场物料", "联合拓客"] }] },
      { layout: "metrics", title: "合作伙伴成效", metrics: [{ label: "平均年收入", value: "¥XXX K" }, { label: "转化率", value: "XX%" }, { label: "支持响应", value: "< 4 小时" }, { label: "伙伴数", value: "XX 家" }] },
      { layout: "timeline", title: "合作启动流程", steps: [{ label: "签约", detail: "合同 + 账户开通" }, { label: "培训", detail: "产品 + 销售方法论" }, { label: "首单", detail: "联合拜访 + 支持" }] },
      { layout: "closing", title: "加入我们的生态", subtitle: "联系渠道负责人", note: "期待携手" },
    ],
  },
  {
    id: "government-bid",
    name: "政府 / 事业单位投标",
    scenario: "政府采购",
    category: "销售提案",
    description: "政府或事业单位采购答辩，强调合规、安全和本土化服务。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "[项目名称] 投标方案", subtitle: "[单位名] · 数字化建设项目", note: "2026" },
      { layout: "bullets", title: "理解与响应需求", bullets: ["充分理解本次采购的核心需求", "我们方案如何完整响应招标要求", "差异化亮点：安全、可靠、可扩展"] },
      { layout: "twoColumn", title: "方案架构", columns: [{ heading: "技术方案", bullets: ["自主可控架构", "国产化适配", "数据本地部署"] }, { heading: "服务方案", bullets: ["本地化服务团队", "7×24 运维保障", "全程陪伴实施"] }] },
      { layout: "metrics", title: "资质与业绩", metrics: [{ label: "类似项目", value: "XX 个" }, { label: "行业经验", value: "X 年" }, { label: "资质认证", value: "X 项" }, { label: "服务客户", value: "XX 家" }] },
      { layout: "timeline", title: "项目计划", steps: [{ label: "启动", detail: "1 个月" }, { label: "实施", detail: "3 个月" }, { label: "验收", detail: "1 个月" }] },
      { layout: "closing", title: "期待共建", subtitle: "专业团队，全程护航", note: "谢谢" },
    ],
  },
  {
    id: "upsell-proposal",
    name: "增值 / 升级销售",
    scenario: "增购与升级",
    category: "销售提案",
    description: "向现有客户推荐高一级方案或新增模块，展示升级价值。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "升级到 [高级方案]", subtitle: "解锁你还没有用到的增长空间", note: "[客户名] 专属" },
      { layout: "bullets", title: "你目前的使用情况", bullets: ["已解锁的核心价值", "当前方案的上限", "你即将遇到的增长瓶颈"] },
      { layout: "twoColumn", title: "升级对比", columns: [{ heading: "当前方案", bullets: ["功能 A", "功能 B", "X 席位限制"] }, { heading: "升级后", bullets: ["功能 A + B + C", "高级分析看板", "无限席位"] }] },
      { layout: "metrics", title: "升级预期收益", metrics: [{ label: "额外效率", value: "+XX%" }, { label: "新增功能", value: "X 项" }, { label: "成本增加", value: "¥XXX/月" }, { label: "预计 ROI", value: "X:1" }] },
      { layout: "closing", title: "立即升级", subtitle: "本月升级享 X 折优惠", note: "联系 CSM" },
    ],
  },
  {
    id: "ecommerce-pitch",
    name: "电商品牌招商 / 入驻",
    scenario: "平台招商",
    category: "销售提案",
    description: "向电商平台或商场展示品牌实力，争取入驻资源位。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "[品牌名] 入驻提案", subtitle: "我们将为平台带来什么", note: "招商 · 2026" },
      { layout: "bullets", title: "品牌简介", bullets: ["品牌定位与核心人群", "已有规模与增速", "核心 SKU 与爆款证明"] },
      { layout: "metrics", title: "品牌数据", metrics: [{ label: "月销售额", value: "¥XXM" }, { label: "复购率", value: "XX%" }, { label: "会员数", value: "XX 万" }, { label: "评分", value: "X.X/5" }] },
      { layout: "twoColumn", title: "合作诉求", columns: [{ heading: "我们期望", bullets: ["首页资源位 X 周", "平台营销活动参与", "物流仓储支持"] }, { heading: "我们承诺", bullets: ["首月 GMV ¥XXX 万", "专属活动策划", "品质保障"] }] },
      { layout: "closing", title: "携手共赢", subtitle: "联系合作负责人", note: "期待入驻" },
    ],
  },
];
