import type { DeckTemplate } from "../types";

export const STRATEGY_TEMPLATES: DeckTemplate[] = [
  {
    id: "company-strategy",
    name: "公司年度战略规划",
    scenario: "战略规划",
    category: "战略规划",
    description: "向全员或管理层发布公司年度战略方向和优先级。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "2027 年公司战略", subtitle: "我们的选择、聚焦与承诺", note: "全员发布 · 2026" },
      { layout: "bullets", title: "战略背景", bullets: ["外部环境变化：3 个关键趋势", "我们的处境：优势与挑战", "为什么现在要做选择"] },
      { layout: "twoColumn", title: "战略定位", columns: [{ heading: "我们是谁", bullets: ["服务谁", "提供什么价值", "如何不同"] }, { heading: "我们不做什么", bullets: ["放弃的市场", "放弃的产品方向", "放弃的客户类型"] }] },
      { layout: "bullets", title: "三大战略优先级", bullets: ["优先级 1：描述 + 衡量标准", "优先级 2：描述 + 衡量标准", "优先级 3：描述 + 衡量标准"] },
      { layout: "metrics", title: "2027 目标", metrics: [{ label: "营收", value: "¥XXM" }, { label: "毛利率", value: "XX%" }, { label: "市占率", value: "XX%" }, { label: "NPS", value: "≥ XX" }] },
      { layout: "timeline", title: "战略节奏", steps: [{ label: "Q1", detail: "夯实基础" }, { label: "Q2–Q3", detail: "规模化增长" }, { label: "Q4", detail: "复盘 + 调整" }] },
      { layout: "closing", title: "我们的承诺", subtitle: "战略不是文件，是每天的选择", note: "一起执行" },
    ],
  },
  {
    id: "market-entry",
    name: "新市场进入策略",
    scenario: "市场拓展",
    category: "战略规划",
    description: "进入新地区或新行业的市场分析与进入策略。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "进入 [新市场] 战略", subtitle: "机会评估 · 进入方式 · 执行计划", note: "战略委员会 · 2026" },
      { layout: "bullets", title: "市场机会", bullets: ["市场规模与增速", "目标客户群特征", "为什么现在是时机"] },
      { layout: "twoColumn", title: "竞争格局", columns: [{ heading: "现有参与者", bullets: ["竞争对手 A：强弱项", "竞争对手 B：强弱项"] }, { heading: "我们的优势", bullets: ["差异化能力", "资源壁垒", "切入路径"] }] },
      { layout: "bullets", title: "进入方式选择", bullets: ["方式 A 自建：成本高、速度慢、控制强", "方式 B 合作：速度快、利润分享", "推荐：XXX，原因 XXX"] },
      { layout: "metrics", title: "预期回报（3年）", metrics: [{ label: "投入", value: "¥XXM" }, { label: "3年营收", value: "¥XXM" }, { label: "ROI", value: "XX%" }, { label: "市占率", value: "XX%" }] },
      { layout: "timeline", title: "进入节奏", steps: [{ label: "0–6 月", detail: "团队 + 合规 + 首批客户" }, { label: "6–18 月", detail: "规模化获客" }, { label: "18–36 月", detail: "盈亏平衡 + 扩张" }] },
      { layout: "closing", title: "决策建议", subtitle: "建议在 [时间] 前做出进入决策", note: "讨论" },
    ],
  },
  {
    id: "ma-strategy",
    name: "并购 / 战略合作评估",
    scenario: "并购与合作",
    category: "战略规划",
    description: "向管理层或董事会呈现并购或战略合作的分析与建议。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "[标的名称] 并购分析", subtitle: "战略价值 · 尽调结论 · 建议", note: "机密 · 2026" },
      { layout: "bullets", title: "战略动因", bullets: ["战略目标与本次并购的契合点", "标的的核心能力与资产", "替代方案比较：自建 vs 合作 vs 并购"] },
      { layout: "metrics", title: "标的概况", metrics: [{ label: "ARR", value: "¥XXM" }, { label: "增速", value: "+XX%" }, { label: "团队规模", value: "XX 人" }, { label: "客户数", value: "XXX" }] },
      { layout: "twoColumn", title: "尽调关键发现", columns: [{ heading: "优势 / 亮点", bullets: ["技术护城河", "客户质量", "团队能力"] }, { heading: "风险 / 问题", bullets: ["负债 / 法律风险", "文化整合难度", "客户集中度"] }] },
      { layout: "metrics", title: "估值与交易结构", metrics: [{ label: "估值区间", value: "¥XX–XXM" }, { label: "支付方式", value: "现金 / 股权" }, { label: "整合周期", value: "X 个月" }, { label: "预期协同", value: "¥XXM/年" }] },
      { layout: "closing", title: "建议", subtitle: "推进 / 暂缓 / 放弃，理由", note: "请董事会决策" },
    ],
  },
  {
    id: "digital-transformation",
    name: "数字化转型规划",
    scenario: "数字化转型",
    category: "战略规划",
    description: "向管理层或董事会展示数字化转型路径、投入与预期价值。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "数字化转型战略", subtitle: "从现状到目标的完整路径", note: "2026–2028" },
      { layout: "bullets", title: "为什么必须转型", bullets: ["市场变化：竞争对手已在做什么", "内部效率损耗有多大", "不转型的代价是什么"] },
      { layout: "twoColumn", title: "现状 vs 目标", columns: [{ heading: "现状", bullets: ["流程手动为主", "数据割裂", "决策依赖经验"] }, { heading: "目标", bullets: ["核心流程自动化", "统一数据中台", "数据驱动决策"] }] },
      { layout: "timeline", title: "三年转型路径", steps: [{ label: "第 1 年", detail: "基础设施 + 数据治理" }, { label: "第 2 年", detail: "流程数字化 + 智能化" }, { label: "第 3 年", detail: "业务创新 + 生态化" }] },
      { layout: "metrics", title: "预期价值", metrics: [{ label: "效率提升", value: "+XX%" }, { label: "成本节省", value: "¥XXM/年" }, { label: "决策速度", value: "快 XX%" }, { label: "总投入", value: "¥XXM" }] },
      { layout: "closing", title: "启动第一阶段", subtitle: "申请预算 · 组建团队 · 锁定目标", note: "数字化是生存问题" },
    ],
  },
  {
    id: "innovation-strategy",
    name: "创新与第二曲线",
    scenario: "业务创新",
    category: "战略规划",
    description: "在主业成熟时探索第二增长曲线的战略框架。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "第二曲线战略", subtitle: "在主业巅峰时开启下一个增长引擎", note: "战略讨论 · 2026" },
      { layout: "bullets", title: "主业现状", bullets: ["主业成熟度：正在触顶的信号", "护城河有多稳：3–5 年内是否仍然有效", "是否有时间窗口投资新业务"] },
      { layout: "twoColumn", title: "机会扫描", columns: [{ heading: "相邻机会", bullets: ["扩展到新客户群", "拓展到新地区", "产品线延伸"] }, { heading: "跨越式机会", bullets: ["颠覆性技术应用", "新商业模式", "生态平台"] }] },
      { layout: "metrics", title: "创新投资组合", metrics: [{ label: "主业守成", value: "70%" }, { label: "相邻创新", value: "20%" }, { label: "颠覆探索", value: "10%" }] },
      { layout: "timeline", title: "探索节奏", steps: [{ label: "0–6 月", detail: "假设验证 + 小额试点" }, { label: "6–18 月", detail: "跑通模型" }, { label: "18–36 月", detail: "规模化" }] },
      { layout: "closing", title: "开始探索", subtitle: "成立创新小组 · 设置独立预算", note: "现在开始" },
    ],
  },
];

export const HR_TEMPLATES: DeckTemplate[] = [
  {
    id: "team-intro",
    name: "团队介绍 / 招聘",
    scenario: "雇主品牌",
    category: "HR与组织",
    description: "对外介绍团队、文化与机会，吸引优秀人才。",
    themeId: "sand",
    slides: [
      { layout: "cover", title: "和我们一起，把卓越复制出去", subtitle: "我们是谁，为什么值得加入", note: "招聘 · 2026" },
      { layout: "bullets", title: "我们的使命", bullets: ["把判断变成组织能力", "让团队独立交付结果", "做反脆弱的组织"] },
      { layout: "twoColumn", title: "我们看重", columns: [{ heading: "价值观", bullets: ["证据优先", "可复制", "长期主义"] }, { heading: "工作方式", bullets: ["少而精", "高自主", "强复盘"] }] },
      { layout: "metrics", title: "团队", metrics: [{ label: "成员", value: "48" }, { label: "在招", value: "6" }, { label: "城市", value: "3" }, { label: "满意度", value: "4.6/5" }] },
      { layout: "quote", quote: "我们不监督人，我们对齐人。", author: "团队信条" },
      { layout: "closing", title: "加入我们", subtitle: "投递入口 / 联系人", note: "期待你" },
    ],
  },
  {
    id: "performance-review",
    name: "绩效评估反馈",
    scenario: "绩效管理",
    category: "HR与组织",
    description: "一对一绩效评估：成果回顾、能力反馈、发展计划。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "绩效评估", subtitle: "[员工姓名] · 2026 H1", note: "一对一 · 保密" },
      { layout: "twoColumn", title: "目标完成情况", columns: [{ heading: "设定目标", bullets: ["目标 A：XXX", "目标 B：XXX", "目标 C：XXX"] }, { heading: "实际结果", bullets: ["A：超额 / 达成 / 未达 + 数据", "B：结果说明", "C：结果说明"] }] },
      { layout: "bullets", title: "亮点与贡献", bullets: ["最值得肯定的成果 1", "最值得肯定的成果 2", "对团队 / 组织的独特贡献"] },
      { layout: "bullets", title: "成长机会", bullets: ["需要提升的能力领域 1", "需要提升的能力领域 2", "建议的学习 / 实践路径"] },
      { layout: "twoColumn", title: "下半年发展计划", columns: [{ heading: "业务目标", bullets: ["目标 A + 指标", "目标 B + 指标"] }, { heading: "能力发展", bullets: ["技能 X 提升计划", "项目实践机会"] }] },
      { layout: "closing", title: "共同期待", subtitle: "下次回顾时间 · [日期]", note: "支持你成长" },
    ],
  },
  {
    id: "org-restructure",
    name: "组织架构调整方案",
    scenario: "组织变革",
    category: "HR与组织",
    description: "向管理层提交组织架构调整方案，含原因、方案和过渡计划。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "组织架构调整方案", subtitle: "适应新战略的组织设计", note: "高管讨论 · 2026" },
      { layout: "bullets", title: "调整背景", bullets: ["战略变化需要新的组织能力", "现有架构的主要瓶颈", "调整目标：XX 和 XX"] },
      { layout: "twoColumn", title: "现有架构问题", columns: [{ heading: "当前痛点", bullets: ["决策链条过长", "协作摩擦点多", "权责不清晰"] }, { heading: "调整原则", bullets: ["扁平化 + 快速响应", "明确权责", "减少汇报层级"] }] },
      { layout: "bullets", title: "新架构方案", bullets: ["新设 [XX] 部门，职责是 XXX", "[XX] 部门合并 / 拆分，原因 XXX", "汇报关系变化说明"] },
      { layout: "timeline", title: "过渡计划", steps: [{ label: "宣布", detail: "全员沟通 + Q&A" }, { label: "过渡", detail: "岗位对接 + 流程磨合（4 周）" }, { label: "稳定", detail: "正式运作 + 复盘" }] },
      { layout: "closing", title: "请管理层决策", subtitle: "方案 A / B 选择 + 启动时间确认", note: "谢谢" },
    ],
  },
  {
    id: "culture-values",
    name: "企业文化 / 价值观发布",
    scenario: "文化建设",
    category: "HR与组织",
    description: "向全员发布或重申企业核心价值观与文化准则。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "我们相信什么", subtitle: "[公司名] 价值观 · 2026 版", note: "全员发布" },
      { layout: "bullets", title: "为什么现在明确价值观", bullets: ["公司规模扩大，文化需要显性化", "价值观是我们做选择的标准", "它不是口号，而是行为准则"] },
      { layout: "quote", quote: "价值观是当利益冲突时，我们选择什么。", author: "创始人" },
      { layout: "bullets", title: "价值观 1：[名称]", bullets: ["定义：具体说明", "做法：日常行为体现", "反面：不符合的行为"] },
      { layout: "bullets", title: "价值观 2–3：[名称]", bullets: ["[价值观 2]：定义 + 行为", "[价值观 3]：定义 + 行为", "三者关系与优先级"] },
      { layout: "closing", title: "从今天开始", subtitle: "价值观体现在每一个小决定里", note: "共同守护" },
    ],
  },
  {
    id: "talent-review",
    name: "人才盘点 / 继任者规划",
    scenario: "人才管理",
    category: "HR与组织",
    description: "向管理层呈现人才盘点结果与关键岗位继任者规划。",
    themeId: "midnight",
    slides: [
      { layout: "cover", title: "人才盘点报告", subtitle: "2026 年度 · 关键岗位与继任规划", note: "高管保密" },
      { layout: "metrics", title: "人才现状", metrics: [{ label: "关键岗位", value: "XX 个" }, { label: "高潜人才", value: "XX 人" }, { label: "继任备份", value: "XX%" }, { label: "流失风险", value: "X 人" }] },
      { layout: "twoColumn", title: "9 宫格分布", columns: [{ heading: "高绩效高潜力（明星）", bullets: ["姓名 A", "姓名 B"] }, { heading: "高绩效待培养（骨干）", bullets: ["姓名 C", "姓名 D"] }] },
      { layout: "bullets", title: "继任者规划重点", bullets: ["关键岗位 A：1st backup 姓名 + 准备度", "关键岗位 B：1st backup 姓名 + 准备度", "人才缺口：哪些关键岗位无备份"] },
      { layout: "bullets", title: "发展行动计划", bullets: ["高潜人才发展举措", "关键人员保留方案", "外部招募填补缺口计划"] },
      { layout: "closing", title: "管理层共识", subtitle: "请确认发展名单与资源投入", note: "年度评估" },
    ],
  },
];

export const CONSULTING_TEMPLATES: DeckTemplate[] = [
  {
    id: "consulting-diagnosis",
    name: "咨询诊断报告",
    scenario: "咨询交付",
    category: "咨询交付",
    description: "面向客户的组织 / 业务诊断结论与建议。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "组织诊断报告", subtitle: "[客户名] · 现状、风险与路径", note: "咨询交付 · 2026" },
      { layout: "section", title: "诊断", subtitle: "我们看到了什么" },
      { layout: "metrics", title: "健康度评分", metrics: [{ label: "可复制度", value: "41%" }, { label: "依赖风险", value: "高" }, { label: "决策一致", value: "中" }, { label: "知识沉淀", value: "低" }] },
      { layout: "bullets", title: "三个核心发现", bullets: ["关键判断集中在少数人", "缺乏可执行的决策规则", "知识未沉淀为组织资产"] },
      { layout: "twoColumn", title: "风险与影响", columns: [{ heading: "风险", bullets: ["关键人离职", "标准走样"] }, { heading: "影响", bullets: ["交付不稳定", "增长受限"] }] },
      { layout: "timeline", title: "建议路径", steps: [{ label: "0–30 天", detail: "诊断 + 规则化" }, { label: "30–60 天", detail: "手册 + 演练" }, { label: "60–90 天", detail: "授权 + 复审" }] },
      { layout: "closing", title: "建议下一步", subtitle: "从最高风险的一项判断开始转移", note: "Q & A" },
    ],
  },
  {
    id: "strategy-consulting",
    name: "战略咨询交付",
    scenario: "战略咨询",
    category: "咨询交付",
    description: "向客户交付战略咨询项目成果，含诊断、策略与落地建议。",
    themeId: "ink",
    slides: [
      { layout: "cover", title: "战略诊断与建议", subtitle: "[客户名] · 增长战略咨询报告", note: "机密 · 2026" },
      { layout: "section", title: "01", subtitle: "现状与问题" },
      { layout: "bullets", title: "三个关键发现", bullets: ["发现 1：数据支撑 + 业务影响", "发现 2：数据支撑 + 业务影响", "发现 3：数据支撑 + 业务影响"] },
      { layout: "section", title: "02", subtitle: "战略选择" },
      { layout: "twoColumn", title: "战略方案对比", columns: [{ heading: "方案 A", bullets: ["核心逻辑", "预期收益", "主要风险"] }, { heading: "方案 B（推荐）", bullets: ["核心逻辑", "预期收益", "主要风险"] }] },
      { layout: "metrics", title: "推荐方案预期价值", metrics: [{ label: "营收增长", value: "+XX%" }, { label: "成本优化", value: "¥XXM" }, { label: "实现周期", value: "X 个月" }, { label: "成功把握", value: "高 / 中" }] },
      { layout: "timeline", title: "落地路线图", steps: [{ label: "阶段 1", detail: "快速行动（0–90 天）" }, { label: "阶段 2", detail: "核心变革（3–12 个月）" }, { label: "阶段 3", detail: "巩固与优化（12 个月+）" }] },
      { layout: "closing", title: "推荐下一步", subtitle: "启动行动 + 指定执行负责人", note: "Q & A" },
    ],
  },
  {
    id: "process-optimization",
    name: "流程优化方案",
    scenario: "流程咨询",
    category: "咨询交付",
    description: "业务流程诊断与优化建议，量化改进空间。",
    themeId: "aurora",
    slides: [
      { layout: "cover", title: "流程优化报告", subtitle: "[流程名称] · 问题、方案与收益", note: "咨询交付 · 2026" },
      { layout: "metrics", title: "现状诊断", metrics: [{ label: "平均耗时", value: "XX 天" }, { label: "错误率", value: "XX%" }, { label: "人工节点", value: "XX 个" }, { label: "成本", value: "¥XXX/次" }] },
      { layout: "bullets", title: "主要痛点", bullets: ["痛点 1：具体描述 + 频率", "痛点 2：具体描述 + 影响", "痛点 3：根本原因"] },
      { layout: "twoColumn", title: "优化方案", columns: [{ heading: "流程重设计", bullets: ["去掉节点 A（无价值）", "合并节点 B+C", "自动化节点 D"] }, { heading: "工具支撑", bullets: ["引入系统 X", "数据打通 Y+Z", "审批线上化"] }] },
      { layout: "metrics", title: "优化后预期", metrics: [{ label: "耗时压缩", value: "→ X 天" }, { label: "错误率", value: "→ X%" }, { label: "人工节点", value: "→ X 个" }, { label: "成本降低", value: "XX%" }] },
      { layout: "closing", title: "落地建议", subtitle: "从高频高价值流程开始，6 周见效", note: "期待推进" },
    ],
  },
  {
    id: "post-project-review",
    name: "项目结案报告",
    scenario: "咨询结案",
    category: "咨询交付",
    description: "咨询项目交付后的结案报告，含成果、学习与后续建议。",
    themeId: "mono",
    slides: [
      { layout: "cover", title: "项目结案报告", subtitle: "[项目名] · 成果回顾与后续建议", note: "交付完成 · 2026" },
      { layout: "metrics", title: "项目成果", metrics: [{ label: "交付物", value: "X 份" }, { label: "实现价值", value: "¥XXM" }, { label: "完成率", value: "XX%" }, { label: "客户满意度", value: "X.X/5" }] },
      { layout: "twoColumn", title: "目标达成情况", columns: [{ heading: "已达成", bullets: ["目标 A：结果数据", "目标 B：结果数据"] }, { heading: "部分达成 / 未达", bullets: ["目标 C：原因 + 说明", "目标 D：后续建议"] }] },
      { layout: "bullets", title: "关键学习", bullets: ["对客户业务的最重要洞察", "项目执行中的经验与教训", "下次可以做得更好的地方"] },
      { layout: "bullets", title: "后续行动建议", bullets: ["短期（1–3 个月）：巩固成果的关键行动", "中期（3–12 个月）：深化变革的建议", "长期：持续优化的机制建立"] },
      { layout: "closing", title: "感谢合作", subtitle: "期待下一阶段的持续支持", note: "Q & A" },
    ],
  },
  {
    id: "benchmark-report",
    name: "行业标杆研究报告",
    scenario: "标杆研究",
    category: "咨询交付",
    description: "向客户呈现行业标杆对比分析与差距提升路径。",
    themeId: "forest",
    slides: [
      { layout: "cover", title: "行业标杆研究", subtitle: "[行业] 最佳实践与差距分析", note: "研究报告 · 2026" },
      { layout: "bullets", title: "研究方法", bullets: ["研究范围：X 家标杆企业 + X 家对标", "数据来源：访谈 / 公开数据 / 调研", "分析维度：X 个关键能力维度"] },
      { layout: "metrics", title: "标杆企业平均水平", metrics: [{ label: "维度 A", value: "XX 分" }, { label: "维度 B", value: "XX 分" }, { label: "维度 C", value: "XX 分" }, { label: "综合", value: "XX 分" }] },
      { layout: "twoColumn", title: "差距分析", columns: [{ heading: "领先差距（需弥补）", bullets: ["维度 A：差距 XX 分", "维度 B：差距 XX 分"] }, { heading: "相当 / 领先", bullets: ["维度 C：持平", "维度 D：超前"] }] },
      { layout: "bullets", title: "标杆最佳实践", bullets: ["实践 1：做法 + 效果 + 可借鉴点", "实践 2：做法 + 效果 + 可借鉴点", "实践 3：做法 + 效果 + 可借鉴点"] },
      { layout: "closing", title: "建议聚焦点", subtitle: "优先提升差距最大、价值最高的 2–3 项", note: "期待共同推进" },
    ],
  },
];
