"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function AssetLifecycleControls({ asset }: { asset: { id: string; title: string; ownerName: string; content: unknown; reviewAt: string | null } }) {
  const router = useRouter(); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(asset.title); const [ownerName, setOwner] = useState(asset.ownerName); const [content, setContent] = useState(JSON.stringify(asset.content, null, 2)); const [reviewAt, setReviewAt] = useState(asset.reviewAt?.slice(0, 10) ?? "");
  async function post(url: string, payload: unknown, method = "POST") { setMessage(""); const res = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "保存失败"); router.refresh(); return data; }
  async function feedback(kind: "USED" | "REVISION_REQUESTED" | "CASE_ADDED") { try { await post(`/api/assets/${asset.id}/feedback`, { kind, note }); setMessage("反馈已记录。"); setNote(""); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  async function save() { try { const parsed = JSON.parse(content) as Record<string, unknown>; await post(`/api/assets/${asset.id}`, { title, ownerName, content: parsed, reviewAt: reviewAt ? new Date(`${reviewAt}T00:00:00Z`).toISOString() : null, changeNote: note }); setMessage("已创建新草稿版本，等待重新批准。"); setEditing(false); } catch (error) { setMessage(error instanceof Error ? error.message : "内容必须是有效 JSON"); } }
  return <div className="mt-4 border-t border-slate-800 pt-3"><div className="flex flex-wrap gap-2"><button className="button-secondary !px-2 !py-1 text-xs" onClick={() => feedback("USED")}>标记已使用</button><button className="button-secondary !px-2 !py-1 text-xs" onClick={() => feedback("REVISION_REQUESTED")}>请求修订</button><button className="button-secondary !px-2 !py-1 text-xs" onClick={() => feedback("CASE_ADDED")}>补充案例</button><button className="button-secondary !px-2 !py-1 text-xs" onClick={() => setEditing(!editing)}>{editing ? "收起编辑" : "编辑并生成新版本"}</button></div><input className="mt-2" value={note} onChange={(e) => setNote(e.target.value)} placeholder="使用结果、修订原因或新增案例"/>{editing && <div className="mt-3 space-y-2 rounded-lg bg-slate-950/50 p-3"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="标题"/><input value={ownerName} onChange={(e) => setOwner(e.target.value)} placeholder="所有者"/><input type="date" value={reviewAt} onChange={(e) => setReviewAt(e.target.value)}/><textarea value={content} onChange={(e) => setContent(e.target.value)} rows={12}/><button className="button-primary" onClick={save}>保存为新版本</button></div>}{message && <p className="mt-2 text-xs text-slate-400">{message}</p>}</div>;
}
