"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

export function AuthForm() {
  const router = useRouter(); const search = useSearchParams(); const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const payload = mode === "register" ? { name, email, password, inviteToken: search.get("invite") ?? undefined } : { email, password }; const res = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "登录失败"); router.push("/dashboard"); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "登录失败"); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="card mx-auto mt-12 max-w-md space-y-4"><div><p className="text-sm text-emerald-300">承策</p><h1 className="mt-1 text-2xl font-semibold">{mode === "login" ? "登录工作区" : "创建账号并加入工作区"}</h1></div>{mode === "register" && <input value={name} onChange={(e) => setName(e.target.value)} placeholder="姓名" required/>}<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="邮箱" required/><input value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="密码（至少 8 位）" minLength={8} required/>{error && <p className="text-sm text-rose-400">{error}</p>}<button className="button-primary w-full" disabled={busy}>{busy ? "请稍候…" : mode === "login" ? "登录" : "注册"}</button><button type="button" className="w-full text-slate-400 hover:text-emerald-300" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "没有账号？注册" : "已有账号？登录"}</button></form>;
}
