"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { AssetBody } from "@/domains/types";
import { ShareReportButton } from "@/components/ShareReportButton";
import { StructuredInterviewForm } from "@/components/StructuredInterviewForm";
import { FileUploadForm } from "@/components/FileUploadForm";
import { CapabilityHeatmap } from "@/components/CapabilityHeatmap";
import { AssetLifecycleControls } from "@/components/AssetLifecycleControls";
import { ProjectJourney } from "@/components/ProjectJourney";
import { AssessmentPanel } from "@/components/AssessmentPanel";
import { TwinSimulator } from "@/components/TwinSimulator";
import { DecisionBoard } from "@/components/DecisionBoard";
import { ActivityLog } from "@/components/ActivityLog";
import { ProjectControlPanel } from "@/components/ProjectControlPanel";

type Evidence = { id: string; kind: "INTERVIEW" | "DOCUMENT" | "NOTE"; title: string; sourceName: string; content: string; createdAt: string };
type Capability = { id: string; name: string; description: string; dependencyScore: number; repeatabilityScore: number; riskIfLost: string; ownerName: string; status: string; references: Reference[] };
type Reference = { id: string; quote: string; reason: string; evidence: { title: string } };
type Asset = { id: string; kind: string; title: string; content: unknown; status: string; version: number; ownerName: string; reviewAt: string | null; references: Reference[] };
type Action = { id: string; title: string; description: string; ownerName: string; dueAt: string | null; status: "TODO" | "IN_PROGRESS" | "BLOCKED" | "DONE"; proof: string };
type Snapshot = { id: string; founderDependency: number; knowledgeCoverage: number; decisionConsistency: number; playbookAdoption: number; openRiskCount: number; replicationReadiness: number; resilience: number; globalManagement: number; summary: string; priorities: string[]; createdAt: string };
type Assessment = { id: string; kind: string; headlineScore: number; findings: { metrics: { label: string; value: number }[]; items: { label: string; detail: string; evidenceTitle?: string; quote?: string }[]; recommendations: string[] }; summary: string; createdAt: string };
type Simulation = { id: string; scenario: string; prediction: { prediction: string; effects: { dimension: string; direction: "UP" | "DOWN" | "FLAT"; magnitude: number; rationale: string }[]; risks: string[]; recommendations: string[] }; accuracy: number; createdAt: string };
type DecisionReview = { id: string; outcome: string; analysis: { summary: string; soundness: number; governanceScore: number; lessons: string[]; suggestedRule: string; followUps: { title: string; ownerHint: string }[] }; governanceScore: number; reviewerName: string; createdAt: string };
type Decision = { id: string; title: string; context: string; decision: string; rationale: string; ownerName: string; reversibility: "LOW" | "MEDIUM" | "HIGH"; expectedOutcome: string; status: "OPEN" | "REVIEWING" | "CLOSED"; createdAt: string; reviews: DecisionReview[] };
type Experiment = { id: string; hypothesis: string; method: string; metric: string; ownerName: string; status: "PLANNED" | "RUNNING" | "LEARNED" | "PAUSED"; result: string; nextDecision: string; dueAt: string | null };
type WeeklyReview = { id: string; weekOf: string; outcome: string; evidence: string; risk: string; nextFocus: string };
type Project = { id: string; name: string; description: string; targetUser: string; mvpOutcome: string; successMetric: string; status: string; evidence: Evidence[]; capabilities: Capability[]; assets: Asset[]; actions: Action[]; snapshots: Snapshot[]; assessments: Assessment[]; simulations: Simulation[]; decisions: Decision[]; experiments: Experiment[]; weeklyReviews: WeeklyReview[] };

const kindLabel: Record<string, string> = { INTERVIEW: "访谈", DOCUMENT: "文档", NOTE: "笔记", DECISION_RULE: "决策规则", OPERATING_PRINCIPLE: "运营原则", PLAYBOOK: "行动手册" };
const date = (value: string | null) => value ? new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric" }).format(new Date(value)) : "未设定";
const percent = (value: number) => `${Math.round(value * 100)}%`;
function body(value: unknown): AssetBody | null { return value && typeof value === "object" ? value as AssetBody : null; }

export function ProjectWorkspace({ project }: { project: Project }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const openRisks = project.capabilities.filter((c) => c.dependencyScore >= 0.7 && c.status !== "TRANSFERRED").length;
  const completion = project.actions.length ? project.actions.filter((a) => a.status === "DONE").length / project.actions.length : 0;
  const latest = project.snapshots[0];
  const orderedEvidence = useMemo(() => [...project.evidence].sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)), [project.evidence]);

  async function request(key: string, url: string, method = "POST", payload?: unknown) {
    setBusy(key); setError(""); setNotice("");
    try { const response = await fetch(url, { method, headers: payload ? { "content-type": "application/json" } : undefined, body: payload ? JSON.stringify(payload) : undefined }); const json = await response.json(); if (!response.ok) throw new Error(json.error || "请求失败"); setNotice("已保存。所有结论与变更均已记录在审计日志中。"); router.refresh(); return json; } catch (err) { setError(err instanceof Error ? err.message : "请求失败"); return null; } finally { setBusy(""); }
  }

  return <div className="space-y-7">
    <section className="rounded-2xl border border-emerald-900/60 bg-gradient-to-br from-emerald-950/60 to-slate-900 p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-emerald-300">能力转移项目 · {project.status}</p><h1 className="mt-1 text-3xl font-semibold">{project.name}</h1><p className="mt-2 max-w-3xl text-slate-300">{project.description || "用可信证据识别关键能力，再将其转成团队可执行的规则与手册。"}</p></div><button className="button-primary" disabled={busy === "report"} onClick={() => request("report", `/api/projects/${project.id}/report`)}>{busy === "report" ? "生成中…" : "生成月度报告"}</button></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-4"><Metric label="高风险依赖" value={String(openRisks)} detail="需转移的关键能力" tone="text-amber-300"/><Metric label="行动完成" value={percent(completion)} detail={`${project.actions.filter((a) => a.status === "DONE").length}/${project.actions.length || 0} 已闭环`} tone="text-sky-300"/><Metric label="已批准资产" value={String(project.assets.filter((a) => a.status === "APPROVED").length)} detail="可被团队采用" tone="text-emerald-300"/><Metric label="证据来源" value={String(project.evidence.length)} detail="AI 结论的事实基础" tone="text-violet-300"/></div>
    </section>
    {error && <p className="rounded-lg border border-rose-900 bg-rose-950/50 px-4 py-3 text-sm text-rose-300">{error}</p>}{notice && <p className="rounded-lg border border-emerald-900 bg-emerald-950/40 px-4 py-3 text-sm text-emerald-200">{notice}</p>}
    <ProjectControlPanel project={{ id: project.id, targetUser: project.targetUser, mvpOutcome: project.mvpOutcome, successMetric: project.successMetric, evidenceCount: project.evidence.length, experiments: project.experiments, weeklyReviews: project.weeklyReviews }} actions={project.actions} approvedAssets={project.assets.filter((asset) => asset.status === "APPROVED").length} save={request}/>
    <ProjectJourney evidence={project.evidence.length} capabilities={project.capabilities.length} assets={project.assets.length} actions={project.actions.length}/>
    {latest && <section className="card"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-400">最近月度复制报告 · {date(latest.createdAt)}</p><h2 className="mt-1 text-lg font-semibold">{latest.summary}</h2></div><span className="text-right text-sm"><span className="block text-emerald-300">可复制度 {percent(latest.replicationReadiness)}</span><span className="block text-xs text-slate-500">创始人依赖 {percent(latest.founderDependency)}</span></span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 md:grid-cols-4"><Metric label="可复制度" value={percent(latest.replicationReadiness)} detail="创始人可复制蓝图综合分" tone="text-emerald-300"/><Metric label="知识覆盖" value={percent(latest.knowledgeCoverage)} detail="关键能力已被批准的资产覆盖"/><Metric label="决策一致性" value={percent(latest.decisionConsistency)} detail="批准的决策规则覆盖"/><Metric label="手册落地" value={percent(latest.playbookAdoption)} detail="已完成的转移动作"/></div>{latest.priorities.length > 0 && <ol className="mt-5 list-decimal space-y-1 pl-5 text-sm text-slate-300">{latest.priorities.map((priority) => <li key={priority}>{priority}</li>)}</ol>}<ShareReportButton snapshotId={latest.id}/></section>}
    <div className="grid gap-7 xl:grid-cols-[1.05fr_1fr]">
      <section className="space-y-4"><SectionTitle step="1" title="证据库" text="访谈、已有制度或会议记录是诊断的唯一事实基础。"/><StructuredInterviewForm projectId={project.id} save={request}/><FileUploadForm projectId={project.id}/><EvidenceForm projectId={project.id} busy={busy} save={request}/>{orderedEvidence.length ? <div className="space-y-2">{orderedEvidence.map((item) => <details key={item.id} className="rounded-xl border border-slate-800 bg-slate-900/40 p-4"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-4"><span className="font-medium">{item.title}</span><span className="text-xs text-slate-500">{kindLabel[item.kind]} · {date(item.createdAt)}</span></div><p className="mt-1 truncate text-sm text-slate-500">{item.sourceName || "未注明来源"}</p></summary><p className="mt-3 whitespace-pre-wrap border-t border-slate-800 pt-3 text-sm leading-6 text-slate-300">{item.content}</p></details>)}</div> : <Empty text="先记录一次创始人访谈或上传已有资料。"/>}<button className="button-secondary w-full" disabled={!project.evidence.length || busy === "diagnosis"} onClick={() => request("diagnosis", `/api/projects/${project.id}/diagnosis`)}>{busy === "diagnosis" ? "分析中…" : "从证据识别关键能力与依赖"}</button></section>
      <section className="space-y-4"><SectionTitle step="2" title="能力与依赖地图" text="优先转移“依赖高、可复制低、失去代价大”的能力。"/><CapabilityHeatmap capabilities={project.capabilities}/>{project.capabilities.length ? <div className="space-y-3">{project.capabilities.map((item) => <article key={item.id} className="card"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{item.name}</h3><p className="mt-1 text-sm text-slate-400">{item.description}</p></div><span className="h-fit rounded-full bg-amber-950 px-2 py-1 text-xs text-amber-300">依赖 {percent(item.dependencyScore)}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Small label="可复制性" value={percent(item.repeatabilityScore)}/><Small label="拟任负责人" value={item.ownerName || "待定"}/></div><div className="mt-3 flex items-center gap-2 text-xs"><span className="text-slate-500">转移状态</span><select className="!w-auto !py-1 text-xs" value={item.status} onChange={(e) => request(`cap-${item.id}`, `/api/capabilities/${item.id}`, "PATCH", { status: e.target.value })}><option value="CANDIDATE">候选</option><option value="CONFIRMED">已确认</option><option value="TRANSFERRING">转移中</option><option value="TRANSFERRED">已转移</option></select></div><p className="mt-3 border-t border-slate-800 pt-3 text-sm text-rose-300">若失去：{item.riskIfLost}</p>{item.references.length ? <blockquote className="mt-3 border-l-2 border-emerald-700 pl-3 text-xs text-slate-400">“{item.references[0].quote}”<span className="ml-1 text-slate-500">— {item.references[0].evidence.title}</span></blockquote> : <p className="mt-3 text-xs text-rose-300">该结论尚无可审查引文。</p>}</article>)}</div> : <Empty text="运行诊断后，这里会显示由证据支持的能力地图。"/>}</section>
    </div>
    <section className="space-y-4"><SectionTitle step="3" title="规则与手册" text="每个资产有证据引文、版本、所有者和审批状态；草稿不是组织标准。"/><AssetForm projectId={project.id} evidence={project.evidence} busy={busy} save={request}/>{project.assets.length ? <div className="grid gap-4 lg:grid-cols-2">{project.assets.map((asset) => <AssetCard key={asset.id} asset={asset} busy={busy} approve={() => request(`approve-${asset.id}`, `/api/assets/${asset.id}/approve`)}/>)}</div> : <Empty text="选择证据并生成第一个决策规则或行动手册。"/>}</section>
    <section className="space-y-4"><SectionTitle step="4" title="90 天能力转移行动" text="不做通用项目管理；这里只保留每个依赖如何被交接、演练、授权与验证。"/><ActionForm projectId={project.id} capabilities={project.capabilities} assets={project.assets} busy={busy} save={request}/>{project.actions.length ? <div className="overflow-hidden rounded-xl border border-slate-800"><div className="grid grid-cols-[1.4fr_.7fr_.7fr_auto] gap-3 bg-slate-900 px-4 py-3 text-xs text-slate-500"><span>行动</span><span>负责人</span><span>状态</span><span></span></div>{project.actions.map((action) => <div key={action.id} className="grid grid-cols-[1.4fr_.7fr_.7fr_auto] items-center gap-3 border-t border-slate-800 px-4 py-3 text-sm"><div><p className="font-medium">{action.title}</p><p className="mt-1 truncate text-xs text-slate-500">{action.description}</p>{action.proof && <p className="mt-1 text-xs text-emerald-300">验证：{action.proof}</p>}</div><span className="text-slate-400">{action.ownerName || "待分配"}</span><span className={action.status === "DONE" ? "text-emerald-300" : action.status === "BLOCKED" ? "text-rose-300" : "text-amber-300"}>{action.status}</span><button className="button-secondary !px-2 !py-1 text-xs" disabled={busy === `action-${action.id}`} onClick={() => request(`action-${action.id}`, `/api/actions/${action.id}`, "PATCH", { status: action.status === "DONE" ? "IN_PROGRESS" : "DONE", proof: action.status === "DONE" ? "" : "负责人已完成交接并提供验证。" })}>{action.status === "DONE" ? "重开" : "完成"}</button></div>)}</div> : <Empty text="诊断会提出初步行动；也可以手动添加。"/>}</section>
    <AssessmentPanel projectId={project.id} assessments={project.assessments} canRun/>
    <TwinSimulator projectId={project.id} simulations={project.simulations} canRun/>
    <DecisionBoard projectId={project.id} decisions={project.decisions} canRun/>
    <ActivityLog projectId={project.id}/>
  </div>;
}

function EvidenceForm({ projectId, busy, save }: { projectId: string; busy: string; save: (key: string, url: string, method?: string, payload?: unknown) => Promise<unknown> }) {
  const [kind, setKind] = useState<"INTERVIEW" | "DOCUMENT" | "NOTE">("INTERVIEW"); const [title, setTitle] = useState(""); const [sourceName, setSourceName] = useState(""); const [content, setContent] = useState("");
  return <form className="card space-y-3" onSubmit={async (e) => { e.preventDefault(); const result = await save("evidence", `/api/projects/${projectId}/evidence`, "POST", { kind, title, sourceName, content }); if (result) { setTitle(""); setSourceName(""); setContent(""); } }}><div className="grid gap-3 sm:grid-cols-3"><select value={kind} onChange={(e) => setKind(e.target.value as typeof kind)}><option value="INTERVIEW">创始人访谈</option><option value="DOCUMENT">已有文档</option><option value="NOTE">观察笔记</option></select><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="证据标题" required/><input value={sourceName} onChange={(e) => setSourceName(e.target.value)} placeholder="来源/访谈对象"/></div><textarea value={content} onChange={(e) => setContent(e.target.value)} rows={5} minLength={20} placeholder="只记录事实、原话、决策背景和具体案例。不要在这里写希望 AI 得出的结论。" required/><button className="button-primary" disabled={busy === "evidence"}>{busy === "evidence" ? "保存中…" : "保存证据"}</button></form>;
}

function AssetForm({ projectId, evidence, busy, save }: { projectId: string; evidence: Evidence[]; busy: string; save: (key: string, url: string, method?: string, payload?: unknown) => Promise<unknown> }) {
  const [kind, setKind] = useState<"DECISION_RULE" | "OPERATING_PRINCIPLE" | "PLAYBOOK">("DECISION_RULE"); const [title, setTitle] = useState(""); const [capability, setCapability] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  const toggle = (id: string) => setSelected((all) => all.includes(id) ? all.filter((x) => x !== id) : [...all, id]);
  return <form className="card space-y-3" onSubmit={async (e) => { e.preventDefault(); const result = await save("asset", `/api/projects/${projectId}/assets`, "POST", { kind, title, capability, evidenceIds: selected }); if (result) { setTitle(""); setCapability(""); setSelected([]); } }}><div className="grid gap-3 md:grid-cols-3"><select value={kind} onChange={(e) => setKind(e.target.value as typeof kind)}><option value="DECISION_RULE">决策规则</option><option value="OPERATING_PRINCIPLE">运营原则</option><option value="PLAYBOOK">行动手册</option></select><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="资产标题" required/><input value={capability} onChange={(e) => setCapability(e.target.value)} placeholder="对应关键能力" required/></div><fieldset><legend className="label">选择事实来源（至少一条）</legend><div className="flex flex-wrap gap-2">{evidence.map((item) => <label key={item.id} className={`cursor-pointer rounded-full border px-3 py-1 text-xs ${selected.includes(item.id) ? "border-emerald-500 bg-emerald-950 text-emerald-200" : "border-slate-700 text-slate-400"}`}><input className="sr-only" type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)}/>{item.title}</label>)}</div></fieldset><button className="button-primary" disabled={!selected.length || busy === "asset"}>{busy === "asset" ? "起草中…" : "生成可审批草稿"}</button></form>;
}

function ActionForm({ projectId, capabilities, assets, busy, save }: { projectId: string; capabilities: Capability[]; assets: Asset[]; busy: string; save: (key: string, url: string, method?: string, payload?: unknown) => Promise<unknown> }) {
  const [title, setTitle] = useState(""); const [ownerName, setOwner] = useState(""); const [description, setDescription] = useState(""); const [capabilityId, setCapability] = useState(""); const [dueAt, setDueAt] = useState("");
  return <form className="card space-y-3" onSubmit={async (e) => { e.preventDefault(); const result = await save("action", `/api/projects/${projectId}/actions`, "POST", { title, ownerName, description, capabilityId: capabilityId || undefined, dueAt: dueAt ? new Date(`${dueAt}T00:00:00Z`).toISOString() : undefined }); if (result) { setTitle(""); setOwner(""); setDescription(""); setCapability(""); setDueAt(""); } }}><div className="grid gap-3 md:grid-cols-4"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="转移动作" required/><input value={ownerName} onChange={(e) => setOwner(e.target.value)} placeholder="负责人"/><input type="date" value={dueAt} onChange={(e) => setDueAt(e.target.value)} aria-label="截止日期"/><select value={capabilityId} onChange={(e) => setCapability(e.target.value)}><option value="">关联能力（可选）</option>{capabilities.map((capability) => <option key={capability.id} value={capability.id}>{capability.name}</option>)}</select></div><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={2} placeholder="什么叫完成？需要哪些交接或演练证据？"/><button className="button-secondary" disabled={busy === "action"}>{busy === "action" ? "保存中…" : "添加行动"}</button></form>;
}

function AssetCard({ asset, busy, approve }: { asset: Asset; busy: string; approve: () => Promise<unknown> }) { const value = body(asset.content); return <article className="card"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-slate-500">{kindLabel[asset.kind]} · v{asset.version}</p><h3 className="mt-1 font-semibold">{asset.title}</h3></div><span className={`rounded-full px-2 py-1 text-xs ${asset.status === "APPROVED" ? "bg-emerald-950 text-emerald-300" : "bg-amber-950 text-amber-300"}`}>{asset.status === "APPROVED" ? "已批准" : "待批准"}</span></div>{value && <div className="mt-4 space-y-3 text-sm"><p className="text-slate-300">{value.purpose}</p><div className="grid gap-2 sm:grid-cols-2"><Small label="何时使用" value={value.whenToUse}/><Small label="所有者" value={value.owner}/><Small label="触发条件" value={value.trigger}/><Small label="复审日期" value={date(asset.reviewAt)}/></div><ol className="list-decimal space-y-1 pl-5 text-slate-400">{value.steps?.map((step, index) => <li key={`${step}-${index}`}>{step}</li>)}</ol><p className="text-xs text-slate-500">完成标准：{value.doneWhen}</p><p className="text-xs text-slate-500">例外：{value.exceptions?.join("；") || "无"}</p></div>}<div className="mt-4 border-t border-slate-800 pt-3"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">证据引文</p>{asset.references.length ? asset.references.map((ref) => <blockquote key={ref.id} className="mt-2 border-l-2 border-emerald-700 pl-3 text-xs text-slate-400">“{ref.quote}”<span className="ml-1 text-slate-500">— {ref.evidence.title} · {ref.reason}</span></blockquote>) : <p className="mt-2 text-xs text-rose-300">草稿缺少可验证引文，不能批准。</p>}</div>{asset.status !== "APPROVED" && <button className="button-primary mt-4" disabled={!asset.references.length || busy === `approve-${asset.id}`} onClick={approve}>{busy === `approve-${asset.id}` ? "批准中…" : "批准为组织标准"}</button>}<AssetLifecycleControls asset={asset}/></article>; }
function Metric({ label, value, detail, tone = "text-slate-100" }: { label: string; value: string; detail: string; tone?: string }) { return <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-semibold ${tone}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }
function Small({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-300">{value}</p></div>; }
function SectionTitle({ step, title, text }: { step: string; title: string; text: string }) { return <div><p className="text-xs font-medium uppercase tracking-wider text-emerald-400">{step}</p><h2 className="mt-1 text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-400">{text}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-slate-800 px-4 py-6 text-sm text-slate-500">{text}</div>; }
