"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Member = { userId: string; role: "OWNER" | "ADMIN" | "MEMBER" | "ADVISOR" | "VIEWER"; user: { name: string | null; email: string } };
export function WorkspaceSettings({ workspaceId, members, subscription }: { workspaceId: string; members: Member[]; subscription: { plan: string; seats: number; status: string } | null }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [role, setRole] = useState("MEMBER"); const [notice, setNotice] = useState(""); const [plan, setPlan] = useState(subscription?.plan ?? "DIAGNOSTIC"); const [seats, setSeats] = useState(subscription?.seats ?? 3);
  async function call(url: string, payload?: unknown, method = "POST") { const res = await fetch(url, { method, headers: payload ? { "content-type": "application/json" } : undefined, body: payload ? JSON.stringify(payload) : undefined }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "操作失败"); router.refresh(); return data; }
  async function checkout(event: React.FormEvent) { event.preventDefault(); try { const data = await call("/api/billing/checkout", { workspaceId, plan, seats: Number(seats) }); window.location.assign(data.url); } catch (error) { setNotice(error instanceof Error ? error.message : "无法发起结账"); } }
  async function portal() { try { const data = await call("/api/billing/portal", { workspaceId }); window.location.assign(data.url); } catch (error) { setNotice(error instanceof Error ? error.message : "无法打开订阅管理"); } }
  return <div className="space-y-7"><section className="card"><h2 className="text-lg font-semibold">邀请成员</h2><form className="mt-4 flex flex-wrap gap-2" onSubmit={async (e) => { e.preventDefault(); try { const data = await call(`/api/workspaces/${workspaceId}/invites`, { email, role }); setNotice(data.joinUrl ? `邀请链接：${data.joinUrl}` : "成员已加入"); setEmail(""); } catch (error) { setNotice(error instanceof Error ? error.message : "操作失败"); } }}><input className="max-w-sm" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="成员邮箱" required/><select className="max-w-32" value={role} onChange={(e) => setRole(e.target.value)}>{["ADMIN", "MEMBER", "ADVISOR", "VIEWER"].map((item) => <option key={item}>{item}</option>)}</select><button className="button-primary">生成邀请</button></form>{notice && <p className="mt-3 break-all text-sm text-emerald-300">{notice}</p>}<div className="mt-5 divide-y divide-slate-800">{members.map((member) => <div key={member.userId} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{member.user.name || member.user.email}</p><p className="text-sm text-slate-500">{member.user.email}</p></div><div className="flex items-center gap-2"><select value={member.role} disabled={member.role === "OWNER"} onChange={async (e) => { try { await call(`/api/workspaces/${workspaceId}/members`, { userId: member.userId, role: e.target.value }, "PATCH"); } catch (error) { setNotice(error instanceof Error ? error.message : "操作失败"); } }}>{(member.role === "OWNER" ? ["OWNER"] : ["ADMIN", "MEMBER", "ADVISOR", "VIEWER"]).map((item) => <option key={item}>{item}</option>)}</select>{member.role !== "OWNER" && <button className="button-secondary !px-2 !py-1" onClick={async () => { if (!confirm(`确定移除 ${member.user.name || member.user.email}？`)) return; try { await call(`/api/workspaces/${workspaceId}/members?userId=${member.userId}`, undefined, "DELETE"); } catch (error) { setNotice(error instanceof Error ? error.message : "操作失败"); } }}>移除</button>}</div></div>)}</div></section><section className="card"><h2 className="text-lg font-semibold">订阅与席位</h2><p className="mt-1 text-sm text-slate-400">通过 Stripe 的托管结账完成订阅；支付成功后 webhook 才会激活或变更组织权益。</p><form className="mt-4 flex flex-wrap gap-2" onSubmit={checkout}><select value={plan} onChange={(e) => setPlan(e.target.value)}><option value="DIAGNOSTIC">诊断版</option><option value="DELIVERY">落地版</option><option value="CONTINUITY">持续订阅</option></select><input className="max-w-28" type="number" min={1} value={seats} onChange={(e) => setSeats(Number(e.target.value))}/><button className="button-primary">前往安全结账</button>{subscription?.status === "active" && <button type="button" className="button-secondary" onClick={portal}>管理订阅</button>}</form></section></div>;
}
