import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { getUserId } from "@/lib/auth";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const userId = await getUserId();
  const workspaces = await prisma.workspace.findMany({ where: { members: { some: { userId } } }, include: { projects: { include: { _count: { select: { evidence: true, assets: true, actions: true } }, snapshots: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" } } }, orderBy: { updatedAt: "desc" } });
  const due = await prisma.systemAsset.findMany({ where: { reviewAt: { lte: new Date() }, status: "APPROVED", project: { workspace: { members: { some: { userId } } } } }, include: { project: { select: { id: true, name: true } } }, take: 8, orderBy: { reviewAt: "asc" } });
  return <AppShell><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-emerald-300">Founder Transfer System</p><h1 className="mt-1 text-3xl font-semibold">把判断，变成组织能力。</h1><p className="mt-2 text-slate-400">从证据到手册、行动和复盘，追踪创始人依赖真正是否下降。</p></div><Link className="button-primary" href="/setup">新建项目</Link></div>{due.length > 0 && <section className="card mt-6 border-amber-900/60"><h2 className="font-semibold text-amber-200">需要复审的组织资产</h2><div className="mt-3 space-y-2">{due.map((asset) => <Link className="block text-sm text-slate-300 hover:text-emerald-300" href={`/projects/${asset.project.id}`} key={asset.id}>{asset.project.name} · {asset.title}（复审日期 {asset.reviewAt?.toLocaleDateString("zh-CN")}）</Link>)}</div></section>}{workspaces.length === 0 ? <div className="card mt-8"><h2 className="text-lg font-semibold">还没有工作区</h2><p className="mt-2 text-slate-400">先建立公司边界，再开始第一项能力转移。</p><Link className="button-primary mt-4 inline-block" href="/setup">创建工作区</Link></div> : <div className="mt-8 space-y-7">{workspaces.map((workspace) => <section key={workspace.id}><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-medium uppercase tracking-wide text-slate-500">{workspace.name}</h2><Link className="text-sm text-slate-400 hover:text-emerald-300" href={`/workspaces/${workspace.id}`}>成员与订阅设置</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{workspace.projects.map((project) => { const snapshot = project.snapshots[0]; return <Link key={project.id} href={`/projects/${project.id}`} className="card block hover:border-emerald-700"><div className="flex justify-between gap-3"><h3 className="font-semibold">{project.name}</h3><span className="text-xs text-slate-500">{project.status}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-400">{project.description || "尚未添加项目背景"}</p><div className="mt-4 flex gap-4 text-xs text-slate-500"><span>{project._count.evidence} 条证据</span><span>{project._count.assets} 个系统资产</span><span>{project._count.actions} 项行动</span></div>{snapshot && <p className="mt-4 border-t border-slate-800 pt-3 text-sm text-emerald-300">创始人依赖 {(snapshot.founderDependency * 100).toFixed(0)}%</p>}</Link>; })}</div></section>)}</div>}</AppShell>;
}
